chef/supermarket

- app/helpers/custom_url_helper.rb
- app/views/layouts/application.html.erb
> Fix incorrect training URL.

- app/views/pages/dashboard.html.erb
- app/views/pages/welcome.html.erb
Also, it's bad to send people to the Chinese wiki :grin:
> Remove old Wiki links and redirect to sensible replacement content.

- README.md
Fix some opscodisms while at it.
> Rewrite readme copy to reflect current state.

- CONTRIBUTING.md
also update some URLs to use HTTPS where appropriate.
> use new mailing lists URL in CONTRIBUTING.md

- app/models/curry/unauthorized_commit_author_comment.rb
> using an absolute url in the model rather than a helper method

- OWNERS
Corrects the owners file so that Kirt and I are listed.
> correcting OWNERS file to reflect current ownership

- app/controllers/cookbook_versions_controller.rb
- config/initializers/paperclip.rb
- docs/CONFIGURING.md
- spec/controllers/cookbook_versions_controller_spec.rb
> Temporary urls for private s3 storage

- app/helpers/markdown_helper.rb
- spec/helpers/markdown_helper_spec.rb
> close a XSS hole

- app/workers/oauth_token_refresh_worker.rb
- spec/workers/oauth_token_refresh_worker_spec.rb
> Fix custom chef oauth2 url

- app/assets/javascripts/advancedSearch.js
- app/assets/javascripts/application.js
- app/assets/javascripts/searchToggle.js
- app/assets/stylesheets/cookbooks/search.scss
- app/controllers/cookbooks_controller.rb
- app/models/cookbook.rb
- app/views/application/_search.html.erb
- spec/controllers/cookbooks_controller_spec.rb
- spec/models/cookbook_spec.rb
This starts work on issue #980.
I thought that I make my work so far public, in a hope of some feedback and ideas on how it should look like.
Idea is to add some kind of search filter where you could choose which platforms you want to include in search result.
> Search based on supported platforms

- app/models/cookbook.rb
- spec/models/cookbook_spec.rb
> transfer ownership creates a collaborator record for the previous owner.

- README.md
Updates the README to remove obsolete information/communication channels.
> remove obsolete links/info from the README

- CHANGELOG.md
- config/initializers/paperclip.rb
- docs/CONFIGURING.md
> Ability to specify s3 bucket paths

- app/models/curry/pull_request_annotator.rb
- spec/models/curry/pull_request_annotator_spec.rb
@kirtfitzpatrick please can you review and release this asap? Sorry.
> disable maintainer assignment for now

- MAINTAINERS.md
- MAINTAINERS.toml
- OWNERS
- lib/tasks/maintainers.rake
Adding in a MAINTAINERS.toml file. 
Fix for #1022
> convert owners file to maintainers file

- app/views/application/_announcement_banner.html.erb
(For discussion.)
Ideally I'd like to see us publicize the results of the cookbook survey and replace the copy here with a link to those results, but I leave that up to @nathenharvey
> As the cookbooks survey is closed, the link should be removed.

- app/views/profile/edit.html.erb
> Added copy around updating your client key

- docs/CONFIGURING.md
Add in documentation around debugging a Supermarket install.
> adding in instructions around debugging a Supermarket install

- app/views/pages/welcome.html.erb
> adding in link to feedback.chef.io

- app/assets/stylesheets/cookbooks/directory.scss
- app/views/cookbooks/_cookbook.html.erb
- app/views/cookbooks/_sidebar.html.erb
- app/views/cookbooks/directory.html.erb
- app/views/cookbooks/index.html.erb
- spec/features/cookbook_directory_spec.rb
> removing references to download count in UI

- app/mailers/adoption_mailer.rb
- app/views/adoption_mailer/interest_email.html.erb
- app/views/adoption_mailer/interest_email.text.erb
- spec/mailers/adoption_mailer_spec.rb
> Enhance adoption email

- docs/CONFIGURING.md
> adding in mention of mailing service to the configuring docs

- README.md
> updating supermarket omnibus instructions

- MAINTAINERS.md
- MAINTAINERS.toml
- ROADMAP.md
To reflect current Supermarket team and current roadmap
> Correcting maintainers and roadmap files

- app/views/adoption_mailer/interest_email.html.erb
- app/views/adoption_mailer/interest_email.text.erb
- spec/mailers/adoption_mailer_spec.rb
> correct url for cookbook up for adoption in adoption emails

- app/models/ccla_signature.rb
- app/models/concerns/exportable.rb
- app/models/icla_signature.rb
- lib/tasks/signers.rake
- spec/factories/ccla_signature.rb
- spec/models/ccla_signature_spec.rb
- spec/models/icla_signature_spec.rb
- spec/support/shared_examples/exportable_spec.rb
Refactored some query logic in the Signatures scopes to allow looking up the earliest a user or organization signed a CLA.
Added rake tasks to export users/organizations based on whether their first CLA signature comes after a given date.
Example usage:
Individual contributors:
```
» be rake signers:export:icla date="2015-07-01"
id,user_id,signed_at,prefix,first_name,middle_name,last_name,suffix,email,phone,address_line_1,address_line_2,city,state,zip,country,icla_id
3,3,2015-08-01 20:22:09 UTC,,Jarod,,Fadel,,jarodfadel@considine.org,(555) 555-5555,1 Main St.,,Whoville,NY,12345,USA,1
4,4,2015-09-04 07:44:22 UTC,,Florine,,Steuber,,florinesteuber@borer.name,(555) 555-5555,1 Main St.,,Whoville,NY,12345,USA,1
6,6,2015-07-14 13:14:01 UTC,,Adaline,,Gulgowski,,adalinegulgowski@schusterfeil.biz,(5 …
```
> Export CLA signatures

- README.md
> fixing no longer true postgres requirement

- CHANGELOG.md
Updates changelog with changes in 2.1.0 release
> updates changelog for 2.1.0 release

- CHANGELOG.md
> Update changelog for 2.1.1-alpha.0

- CONTRIBUTING.md
- MAINTAINERS.md
- MAINTAINERS.toml
Also auto fixed the MD format in the contributing doc and fixed a bunch
of spelling mistakes there.
> Update github URLs and mailing list URLs

- README.md
- you use `bundle exec` above, you should be consistent ;)
> Update README.md with consistent bundle exec

- ROADMAP.md
* Remove LDAP integration
* Add Compliance Profiles
> Update ROADMAP for Q1 2016

- app/models/tool.rb
Could it really be this simple?
I think it is based on 8f9fe9c and 846fc73
> Add Compliance Profile as a tool type

- ROADMAP.md
Update the ROADMAP for Q1 2016
> Compliance Proflie tool type has shipped

- app/views/cookbook_mailer/follower_notification_email.html.erb
- app/views/cookbook_mailer/follower_notification_email.text.erb
> Longer Changelog in Cookbook Follower emails

- .gitignore
* Mac's finder cache
* SASS cache
* direnv's .envrc and project directory when using `layout ruby`
> Add local dev env things to gitignore

- app/assets/stylesheets/dashboard.scss
> removes display:none for links when the screen is under a certain size

- Gemfile.lock
Upgrade to address CVE-2015-7499
https://groups.google.com/forum/#!topic/ruby-security-ann/Dy7YiKb_pMM
> Upgrade nokogiri to address CVE-2015-7499

- app/assets/stylesheets/cookbooks/search.scss
- app/controllers/cookbooks_controller.rb
- app/models/concerns/badgeable.rb
- app/models/cookbook.rb
- app/views/application/_search.html.erb
- spec/controllers/cookbooks_controller_spec.rb
- spec/features/badges_cookbook_partner_spec.rb
Closes #1177 
Mimicks searching for cookbooks by supported platform.
> Add badges to Advanced Search for cookbooks

- README.md
- config/database.yml
- lib/tasks/setup.rake
* README instructions for setting up Docker on Mac OS
* config/database.yml tweak to allow host config via environment variables
> Add rake task to spin up PG & Redis in Docker

- .travis.yml
- README.md
- app/models/cookbook.rb
- app/models/cookbook_upload/metadata.rb
- db/migrate/20160121191223_add_chef_version_and_ohai_version_to_cookbook_version.rb
- db/migrate/20160121191223_add_chef_versions_and_ohai_versions_to_cookbook_version.rb
- db/schema.rb
- spec/models/cookbook_spec.rb
- spec/models/cookbook_upload/metadata_spec.rb
> Add chef and ohai attributes 2

- Gemfile
- Gemfile.lock
- Guardfile
Run your tests automatically, yo.
(Removed replacing Rubocop with chefstyle for the moment.)
> Add guard to run stuff on changes in dev

- app/views/profile/edit.html.erb
> Update steps and links to create/login Chef account to get a key.

- CHANGELOG.md
> Changelog update for 2.5.0

- app/assets/javascripts/cookbookDeprecate.js
- app/views/cookbooks/_manage_cookbook.html.erb
> Change the deprecation form text so that it's clear replacement is optional

- .inch.yml
- README.md
> Fix badges for CodeClimate and InchCI

- src/supermarket/app/helpers/supported_platforms_helper.rb
- src/supermarket/app/views/application/_search.html.erb
Use the standard suse icon. Also while we're here add opensuse to search
> Add opensuseleap support

- README.md
These display better on retina / mobile devices
> Make the readme badges SVGs

- src/supermarket/config/initializers/paperclip.rb
> Make s3 location agnostic

- src/supermarket/app/assets/javascripts/announcementBanner.js
- src/supermarket/app/assets/stylesheets/announcement_banner.css.scss
- src/supermarket/app/views/application/_announcement_banner.html.erb
- src/supermarket/app/views/application/_appheader.html.erb
> Changing announcements to a 'More Information' tab

- src/supermarket/db/seeds/ccla/body.md
> Include Schedule A/B in body to match hard copy.

- src/supermarket/app/models/curry/pull_request_annotator.rb
- src/supermarket/spec/models/curry/pull_request_annotator_spec.rb
- src/supermarket/spec/vcr_cassettes/pull_request_annotation_assigns_maintainer.yml
> remove PR assignment

- src/supermarket/app/views/application/_search.html.erb
This sentence seems really awkward as is.
> Fix odd wording

- src/supermarket/Gemfile.lock
Fixes Brakeman flagged error in Travis runs
> upgrades nokogiri

- src/supermarket/app/helpers/adoption_helper.rb
- src/supermarket/spec/helpers/adoption_helper_spec.rb
Fixes #1315 by adding a confirmation button.
> adds pop-up to confirm putting a cookbook up for adoption

- omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
- src/supermarket/app/helpers/feature_flag_helper.rb
- src/supermarket/app/views/layouts/application.html.erb
- src/supermarket/docs/CONFIGURING.md
- src/supermarket/spec/helpers/feature_flag_helper_spec.rb
> Air gap feature flag

- src/supermarket/app/views/cookbooks/_main.html.erb
> Removes extraneous word in view for passing collaborators metric

- omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
> changes fieri_results_endpoint to fieri_supermarket_endpoint

- src/supermarket/app/controllers/collaborators_controller.rb
- src/supermarket/spec/controllers/collaborators_controller_spec.rb
Fixes #1378 pending testing it out in a Terraform environment.
> Adding collaborator triggers fieri

- src/supermarket/app/models/cookbook.rb
- src/supermarket/spec/models/cookbook_spec.rb
> Refactor transfer process

- .delivery/build_cookbook/recipes/default.rb
- .delivery/build_cookbook/recipes/functional.rb
- .delivery/build_cookbook/recipes/publish.rb
- omnibus/cookbooks/omnibus-supermarket/recipes/config.rb
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/ssl_spec.rb
> Use node.normal instead of node.set

- src/supermarket/app/models/user.rb
- src/supermarket/app/views/cookbooks/_installs.html.erb
We should make it easier for users to cut and paste if using Policyfile
> Replace Librarian tab with Policyfile

- src/supermarket/app/views/cookbooks/_installs.html.erb
> Fix missing quote in the install syntax for policyfile

- omnibus/Gemfile.lock
- omnibus/config/projects/supermarket.rb
Upgrade omnibus-software and omnibus to make openssl v1.0.2h available to
the build.
> Upgrade omnibus'd openssl to 1.0.2h

- src/supermarket/app/assets/stylesheets/structure.scss
Let browsers decide appropriate mouse cursor for a thing.
Closes #1424
> Set mouse cursor to auto on html.body

- src/fieri/app/models/foodcritic_worker.rb
- src/fieri/spec/models/foodcritic_worker_spec.rb
- src/supermarket/app/helpers/cookbooks_helper.rb
- src/supermarket/app/views/cookbooks/_main.html.erb
- src/supermarket/spec/helpers/cookbooks_helper_spec.rb
New version of #1400 
Fixes #1354
> Show fieri version and tags

- src/fieri/spec/models/collaborator_worker_spec.rb
- src/supermarket/app/controllers/api/v1/cookbook_versions_controller.rb
- src/supermarket/spec/controllers/api/v1/cookbook_versions_controller_spec.rb
Small refactor that better lays the foundation for adding more quality metrics.
> Refactor metrics

- .travis.yml
Removing/rotating secrets in the Travis config
> Rotate Travis secrets

- src/fieri/.rubocop_todo.yml
- src/fieri/app/controllers/fieri/jobs_controller.rb
- src/fieri/app/models/publish_worker.rb
- src/fieri/spec/controllers/fieri/jobs_controller_spec.rb
- src/fieri/spec/models/publish_worker_spec.rb
- src/fieri/spec/requests/fieri/fieri_status_spec.rb
- src/fieri/spec/support/cookbook_deprecated_fixture.json
- src/fieri/spec/support/cookbook_does_not_exist.json
- src/fieri/spec/support/cookbook_non_deprecated_fixture.json
- src/fieri/spec/support/cookbook_not_up_for_adoption_fixture.json
- src/fieri/spec/support/cookbook_up_for_adoption_fixture.json
- src/supermarket/app/controllers/api/v1/cookbook_versions_controller.rb
- src/supermarket/app/controllers/cookbook_versions_controller.rb
- src/supermarket/app/controllers/cookbooks_controller.rb
- src/supermarket/app/models/cookbook_version.rb
- src/supermarket/app/models/metric_result.rb
- src/supermarket/app/models/quality_metric.rb
- src/supermarket/app/views/cookbooks/_metrics.html.erb
- src/supermarket/config/routes.rb
- src/supermarket/db/migrate/20161116191103_add_admin_only_to_quality_metrics.rb
- src/supermarket/db/schema.rb
- src/supermarket/db/seeds.rb
- src/supermarket/spec/controllers/api/v1/cookbook_versions_controller_spec.rb
- src/supermarket/spec/controllers/cookbook_versions_controller_spec.rb
- src/supermarket/spec/controllers/cookbooks_controller_spec.rb
- src/supermarket/spec/factories/quality_metric.rb
- src/supermarket/spec/models/quality_metric_spec.rb
> Add admin only quality metric

- CONTRIBUTING.md
Fixes #1465 
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> updated contributing docs to reflect move to DCO

- src/supermarket/app/models/user.rb
- src/supermarket/app/views/profile/edit.html.erb
- src/supermarket/spec/extractors/chef_oauth2_extractor_spec.rb
- src/supermarket/spec/models/user_spec.rb
- src/supermarket/spec/support/omni_auth_control.rb
> Modify key wording

- src/fieri/app/controllers/fieri/jobs_controller.rb
- src/fieri/app/models/collaborator_worker.rb
- src/fieri/app/models/metrics_runner.rb
- src/fieri/app/models/publish_worker.rb
- src/fieri/app/models/supermarket_api_runner.rb
- src/fieri/spec/controllers/fieri/jobs_controller_spec.rb
- src/fieri/spec/models/collaborator_worker_spec.rb
- src/fieri/spec/models/metrics_runner_spec.rb
- src/fieri/spec/models/publish_worker_spec.rb
- src/fieri/spec/models/supermarket_api_runner_spec.rb
- src/fieri/spec/requests/fieri/fieri_jobs_spec.rb
- src/fieri/spec/requests/fieri/fieri_status_spec.rb
- src/fieri/spec/support/cookbook_insufficient_collaborators_fixture.json
- src/fieri/spec/support/cookbook_sufficient_collaborators_fixture.json
> Renovate fieri code

- src/fieri/app/models/publish_worker.rb
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> adds passing message to publish worker results

- src/supermarket/app/views/cookbooks/directory.html.erb
> Fix link to api doc.

- src/fieri/Gemfile.lock
- src/fieri/app/models/contributing_file_worker.rb
- src/fieri/app/models/contributor_file_worker.rb
- src/fieri/app/models/metrics_runner.rb
- src/fieri/config/locales/en.yml
- src/fieri/fieri.gemspec
- src/fieri/spec/models/contributing_file_worker_spec.rb
- src/fieri/spec/models/contributor_file_worker_spec.rb
- src/fieri/spec/models/metrics_runner_spec.rb
- src/fieri/spec/support/cookbook_non_github_source_url_fixture.json
- src/fieri/spec/support/cookbook_null_source_url_fixture.json
- src/fieri/spec/support/cookbook_source_url_fixture.json
- src/fieri/spec/support/github_contributing_file_positive.json
- src/supermarket/Gemfile.lock
- src/supermarket/app/controllers/api/v1/quality_metrics_controller.rb
- src/supermarket/app/models/quality_metric.rb
- src/supermarket/config/locales/en.yml
- src/supermarket/config/routes.rb
- src/supermarket/db/seeds.rb
- src/supermarket/spec/controllers/api/v1/quality_metrics_controller_spec.rb
- src/supermarket/spec/factories/quality_metric.rb
- src/supermarket/spec/models/quality_metric_spec.rb
> Contributing file QM

- src/fieri/app/models/metrics_runner.rb
- src/fieri/spec/models/metrics_runner_spec.rb
Fixes minor bug with the collaborator metric that surfaced when testing the latest release on staging.
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
> fixes bug with collaborator metric

- README.md
- src/fieri/README.md
- src/fieri/README.rdoc
Includes some cleanup of feature flags in the main README
Closes #1536
> add instructions for testing and running quality metrics

- src/fieri/app/models/metrics_runner.rb
- src/fieri/app/models/version_tag_worker.rb
- src/fieri/config/locales/en.yml
- src/fieri/spec/models/metrics_runner_spec.rb
- src/fieri/spec/models/version_tag_worker_spec.rb
- src/fieri/spec/support/github_version_tag_positive.json
- src/fieri/spec/support/github_version_tag_with_v_in_number.json
- src/supermarket/app/controllers/api/v1/quality_metrics_controller.rb
- src/supermarket/app/models/quality_metric.rb
- src/supermarket/config/locales/en.yml
- src/supermarket/config/routes.rb
- src/supermarket/db/seeds.rb
- src/supermarket/spec/controllers/api/v1/quality_metrics_controller_spec.rb
- src/supermarket/spec/factories/quality_metric.rb
- src/supermarket/spec/models/quality_metric_spec.rb
> Add version tag qm

- omnibus/cookbooks/omnibus-supermarket/metadata.rb
- src/fieri/app/models/license_worker.rb
- src/fieri/spec/support/cookbook_version_apache_2_0_license.json
- src/fieri/spec/support/cookbook_version_gnu_public_license_2_0.json
- src/fieri/spec/support/cookbook_version_gnu_public_license_3_0.json
> Accept either SPDX standard licenses or DK generated licenses

- src/fieri/Gemfile.lock
- src/fieri/fieri.gemspec
- src/supermarket/Gemfile.lock
> Use Foodcritic 10.2

- src/fieri/Gemfile.lock
- src/supermarket/Gemfile.lock
> Update to Foodcritic 10.2.2

- src/fieri/app/models/license_worker.rb
Fixes #1585
Signed-off-by: Nathen Harvey <nharvey@chef.io>
> Add additional acceptable license strings

- src/supermarket/app/views/application/_announcement_banner.html.erb
- src/supermarket/app/views/pages/dashboard.html.erb
- src/supermarket/app/views/pages/welcome.html.erb
> direct old google groups links to the chef discourse 

- src/supermarket/Gemfile
- src/supermarket/Gemfile.lock
* APM agents (New Relic & Datadog) upgraded
* Exception reporting agent (Sentry) upgraded
> Update embedded agents

- src/fieri/Gemfile.lock
- src/supermarket/Gemfile.lock
> upgrade foodcritic to 11.2

- src/supermarket/app/views/pages/dashboard.html.erb
- src/supermarket/app/views/pages/welcome.html.erb
> Remove IRC links in favor of Slack

- .delivery/build_cookbook/metadata.rb
- .delivery/build_cookbook/recipes/default.rb
- .delivery/build_cookbook/recipes/publish.rb
- .expeditor/config.yml
Ready to merge? View this change in Chef Automate and click the Approve button: https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/dd9cdc14-3341-455e-b8be-f87a29348759
> Use latest expeditor to fix provision

- .delivery/build_cookbook/libraries/helpers.rb
- .delivery/build_cookbook/metadata.rb
Ready to merge? View this change in Chef Automate and click the Approve button: https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/5754a04b-c782-4508-8307-a88ad97801f1
> Use proper delivery-sugar DSL

- cookbooks/supermarket-deploy/metadata.rb
- cookbooks/supermarket-deploy/recipes/omnibus_standalone.rb
Ready to merge? View this change in Chef Automate and click the Approve button: https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/f012e917-3c85-4c1f-a327-a2bc61fa4634
> Use wildcard SSL cert for ACC environments

- cookbooks/supermarket-deploy/libraries/helpers.rb
- cookbooks/supermarket-deploy/metadata.rb
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/19bf7346-7633-4f4d-a41d-20f0676f55ef) in Chef Automate and click the Approve button.
> Use friendly DNS (no .cd.chef.co)

- .delivery/config.json
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/b9379327-8b6e-4f54-9f67-772cc57dd850) in Chef Automate and click the Approve button.
> Add delivery-truck config (matching Automate)

- README.md
- Found a formatting typo
- Updated the Copyright
Signed-off-by: JJ Asghar <jj@chef.io>
> typo and Copyright

- cookbooks/supermarket-deploy/Berksfile
- cookbooks/supermarket-deploy/metadata.rb
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/64baf82c-609e-4569-9563-144c32784c0a) in Chef Automate and click the Approve button.
> Explicitly define cookbooks in deploy cookbook Berksfile

- .delivery/build_cookbook/Berksfile
- .delivery/build_cookbook/attributes/default.rb
- .delivery/build_cookbook/data_bags/keys/delivery_builder_keys.json
- .delivery/build_cookbook/libraries/helpers.rb
- .delivery/build_cookbook/metadata.rb
- .delivery/build_cookbook/recipes/default.rb
- .delivery/build_cookbook/recipes/provision.rb
- .delivery/build_cookbook/recipes/smoke.rb
- .delivery/build_cookbook/test/fixtures/cookbooks/test/metadata.rb
- .delivery/build_cookbook/test/fixtures/cookbooks/test/recipes/default.rb
- .github/CODEOWNERS
- cookbooks/supermarket-deploy/recipes/omnibus_standalone.rb
- inspec/supermarket-smoke/README.md
- inspec/supermarket-smoke/controls/base.rb
- inspec/supermarket-smoke/inspec.lock
- inspec/supermarket-smoke/inspec.yml
- inspec/supermarket-smoke/libraries/helper.rb
This Pull Request was opened by Chef Automate user Seth Chisamore
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/cb7c1689-cee8-4b99-9a49-132a0250ec58) in Chef Automate and click the Approve button.
> [JEX-623] Add InSpec-based smoke tests for Supermarket

- src/fieri/Gemfile.lock
- src/supermarket/Gemfile.lock
This Pull Request was opened by Chef Automate user Robb Kidd
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/8d3b1a60-1840-4259-8848-93e4e65b2459) in Chef Automate and click the Approve button.
> Use Foodcritic 11.3

- omnibus/Gemfile.lock
- omnibus/config/projects/supermarket.rb
This Pull Request was opened by Chef Automate user Robb Kidd
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/9ac5091a-aa2e-461d-bc0f-7771676803e4) in Chef Automate and click the Approve button.
> update PG to 9.3.18

- .expeditor/config.yml
- .travis.yml
> Update Slack notification channel to #supermarket-notify

- .delivery/build_cookbook/recipes/smoke.rb
This should have been removed as part of chef/supermarket#1657
> Remove stale only_if from smoke recipe

- .expeditor/config.yml
- CHANGELOG.md
> Update Expeditor to meet 0.5.0 requirements

- CONTRIBUTING.md
add some detail about how to:
- run postgres and redis through the `docker-compose.yml` file;
- resolve some potential issues installing the gem bundle;
- run the specs locally;
- run rubocop locally;
> update the contributor guide

- src/supermarket/app/views/cookbooks/directory.html.erb
These all redirected to these updated URLs
> correct the links on the cookbooks page

- src/fieri/Gemfile.lock
- src/supermarket/Gemfile.lock
> Update Foodcritic to 11.4.0

- .delivery/config.json
> Remove dependency on cd-infrastructure

- src/fieri/Gemfile.lock
- src/supermarket/Gemfile.lock
> Update Foodcritic to 12.1

- terraform/u-r-d/omnibus-standalone-inplace-upgrade.tf
Related to chef/es-terraform#28
> Disable API termination for delivered instances

- src/fieri/Gemfile.lock
- src/supermarket/Gemfile.lock
> Use Foodcritic 12.2.1

- .delivery/build_cookbook/attributes/default.rb
- .travis.yml
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Unpin terraform version

- src/fieri/Gemfile.lock
- src/fieri/fieri.gemspec
- src/supermarket/Gemfile.lock
> upgrade Foodcritic to v13.0.0

- src/supermarket/app/assets/stylesheets/branding/README.md
Putting these steps in the README. This is sort of known and shared tribally. This process is not delightful, but writing it down should help others and maybe provide a jumping off point to make it better.
> add example for customizing branding in production

- MAINTAINERS.md
- MAINTAINERS.toml
Hey, the humans maintaining this have changed. We should bring this up to date.
Nell and I have already talked about this change. Some sort of ceremony involving cake is pending planning.
> update maintainers document

- .expeditor/config.yml
Makes for more organized changelog entries.
> map changelog sections to PR labels

- omnibus/config/projects/supermarket.rb
For other projects this reduced package sizes by about 23%
> reduce package size with compression for omnibus DEB & RPM configs

- .expeditor/config.yml
> enable PR branch cleanup by Expeditor

- MAINTAINERS.md
- MAINTAINERS.toml
This also removes @nathenharvey
Signed-off-by: Nathen Harvey <nharvey@chef.io>
> Make @krasnow the project lead

- .expeditor/config.yml
Also, alphabetize that `github:` section.
> enable minor version bumping via GitHub label with expeditor

- .delivery/build_cookbook/recipes/provision.rb
- .delivery/build_cookbook/recipes/smoke.rb
- .expeditor/config.yml
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Replace Jenkins omnibus build/test pipeline with Buildkite

- .expeditor/config.yml
Tell expeditor about the project's new labels so that the changelog gets entries put in meaningful sections.
> update PR label to changelog category mapping

- src/supermarket/habitat/hooks/init
- src/supermarket/habitat/plan.sh
@robbkidd  From our work on hackday
- Added foreman configuration
- Added DB creation to init hook
> Updated hab config to run web and worker

- omnibus/Gemfile.lock
update to use [curl 7.65.0 via updates to omnibus-software](https://github.com/chef/omnibus-software/pull/1056)
> update to use curl 7.65.0

- .expeditor/release.omnibus.yml
- omnibus/Gemfile.lock
> Add EL8 tester to build pipeline

- .delivery/build_cookbook/recipes/deploy.rb
Gotta accept the Chef license in the ACC pipeline's chef-client runs, otherwise the remote CCR times out waiting for the user to say "Yes."
> accept the Chef license in the ACC pipeline's chef-client runs

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
> Add verification to buildkite

- src/supermarket/Gemfile.lock
- src/supermarket/engines/fieri/Gemfile.lock
> update for CVE-2019-13117 & CVE-2019-16782

- README.md
I also fixed some mdlint errors and removed the date from our copyright
> Update required ruby version in the readme

- src/supermarket/Gemfile
- src/supermarket/Gemfile.lock
And only add the library. This will make it available in production-like environments for experimentation without committing yet to a pattern for how to configure it in various permutations (hosted vs the multitude of onprems). Skipping a changelog entry, because the library's mere presence in the release packages does not automatically turn on any functionality in Supermarket.
> add Honeycomb's beeline library

- .travis.yml
- omnibus/cookbooks/omnibus-supermarket/templates/nginx.conf.erb
- src/supermarket/app/lib/supermarket/health.rb
Fix Supermarket's health status check on PostgreSQL 9.6 or greater.
#1829
> support PostgreSQL 9.6+

- docs/cookbookadoptiononsupermarket.md
Got a request from a community member to add more clarification. Added that clarification, and also fixed some phrasing problems.
Signed-off-by: benny Vasquez <bvasquez@chef.io>
> clarification for cookbook transfer policy

- omnibus/omnibus-test.sh
Updated tests to support the use of skip-artifactory-platforms within the shim pipeline definition where packages will be downloaded directly from the buildkite artifacts api.
> Update tests to handle local omnibus packages from Buildkite artifacts api

- .expeditor/release.omnibus.yml
- omnibus/.kitchen.yml
- omnibus/cookbooks/omnibus-supermarket/.kitchen.yml
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/app_spec.rb
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/config_spec.rb
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/database_spec.rb
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/nginx_spec.rb
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/postgresql_spec.rb
- omnibus/cookbooks/omnibus-supermarket/spec/recipes/redis_spec.rb
> Stop producing Ubuntu 16.04 packages

- omnibus/Gemfile.lock
> Bump all omnibus deps to the latest

- .travis.yml
Lint was moved to GitHub actions
> Limit the tests that run on Travis

- src/supermarket/Gemfile
- src/supermarket/Gemfile.lock
This should be the only thing we actually need
> Swap the full AWS SDK for just the S3 dep

- .github/workflows/unit.yml
- src/supermarket/config/database.yml
> Run unit tests in GitHub Actions

- .github/workflows/brakeman-analysis.yml
This way we can remove it from the actual Gemfile
> Setup Brakeman as a GitHub Action

- src/supermarket/Gemfile
- src/supermarket/Gemfile.lock
This is handled outside the gemfile in GitHub Actions now
> Remove brakeman from the gemfile

- CONTRIBUTING.md
- README.md
I'm trying to follow these docs to get started so I'm updating as I go.
> Start the process of rewriting the contributing docs

- src/supermarket/app/views/application/_search.html.erb
Removed the outdated platforms from advanced options
Updated the platform list in search page
https://github.com/chef/supermarket/issues/1973
> Updated platform list for advanced search option

- src/supermarket/app/helpers/custom_url_helper.rb
- src/supermarket/spec/helpers/custom_url_helper_spec.rb
Chef blog url was not pointing to correct url. URL link changes to avoid redirection
https://github.com/chef/supermarket/issues/1966
> Changes for blog url link change

- .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
- .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
- .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add github issue/PR templates

- omnibus/Gemfile.lock
> Update omnibus / omnibus-software to the latest

- omnibus/Gemfile.lock
> Fix Ruby 2.6.8 compilation

- docs/setup_test_env_in_local.md
Added documentation for steps to setup test environment in local for supermarket.
> Created documentation for setting up test env in local for supermarket

- src/supermarket/app/lib/supermarket/s3_config.rb
Make sure to print out what was provided so that it's more clear what needs to be set still.
> Improve error message when S3 environmental variables are not correct

- habitat/README.md
- habitat/default.toml
- habitat/plan.sh
Delete the incomplete habitat plan
Fixes https://github.com/chef/supermarket/issues/1961
> Delete the incomplete habitat plan

- .github/workflows/ctl-cookbook-testing.yml
- omnibus/Gemfile.lock
- omnibus/cookbooks/omnibus-supermarket/Gemfile
This is all terrible and it needs to get refactored away, but it's the
way we do it today.
> Add back the gemfile to fix build failures

- omnibus/package-scripts/supermarket/postinst
> Supermarket -> Chef Supermarket in the installer

- .github/CODEOWNERS
> Add all the teams to the GitHub codeowners file

- src/supermarket/Gemfile.lock
- src/supermarket/engines/fieri/Gemfile.lock
- src/supermarket/engines/fieri/fieri.gemspec
We're not using this at this point so let's not bundle / ship it to everyone.
> Remove unused Cookstyle dep in fieri

- omnibus/config/software/supermarket-cookbooks.rb
This worked before. Let's get it to work again.
> Remove the gem install of Berkshelf

- .expeditor/release.omnibus.yml
> Produce EL 8 specific pacakges

- omnibus/config/projects/supermarket.rb
- omnibus/config/software/supermarket.rb
> Exclude additional files from the Supermarket install

- omnibus/config/software/supermarket.rb
> Remove chef-gem dependency entirely

- omnibus/config/software/more-ruby-cleanup-supermarket.rb
Make sure we expand the path first so this works
> Fix the cleanup of cached gems

- src/supermarket/app/views/tools/directory.html.erb
> Update tools copy to not mention Foodcritic

- omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
> Update copy in the supermarket.rb config file

- README.md
- src/supermarket/docker-compose.yml
-- This change refers to the major version change in `Redis` that we did in https://github.com/chef/omnibus-software/pull/1430 
Related issue : https://github.com/chef/supermarket/issues/1952
> Redis major upgrade 

- .expeditor/announce-release.sh
- .expeditor/config.yml
Pretty sure we need to modernize this whole config.
@tduffield Is this the old config format that needs to get reworked?
> Automate release announcements + minor expeditor config updates

- .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/brakeman-analysis.yml
- .github/workflows/ctl-cookbook-testing.yml
- .github/workflows/unit.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- omnibus/CONTRIBUTING.md
- omnibus/config/projects/supermarket.rb
- omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
- src/supermarket/Rakefile
> Switch to main branch

- omnibus/config/software/supermarket-ctl.rb
Signed-off-by: Swati Keshari <skeshari@msystechnologies.com>
> Replace deprecated --without flag with bundle config

- src/supermarket/app/views/profile/edit.html.erb
- src/supermarket/vendor/assets/stylesheets/foundation.css
Added div style to introduce scrollbar to contributor table in `Manage Profile` page. 
Added a new style and applied it to the table
https://github.com/chef/supermarket/issues/2139
> Changes for applying scrollbar to contributors table

- omnibus/Gemfile.lock
- omnibus/config/projects/supermarket.rb
> Update openssl to 1.0.2za

- src/supermarket/app/views/pages/dashboard.html.erb
Signed-off-by: Dheeraj Singh Dubey <dhsingh@progress.com>
Remove `Contribute to Supermarket` link
Fixes https://github.com/chef/supermarket/issues/2185
> Remove Contribute to Supermarket link

- src/supermarket/app/views/cookbooks/_sidebar.html.erb
Platforms text changed to Supported Platforms
#2230
> Platforms text changed to Supported Platforms

- src/supermarket/app/views/users/_sidebar.html.erb
- Updated profile sidebar hover text to joined Supermarket.
#2186
> Updated profile sidebar hover over text to not mention the legacy community site

- .expeditor/config.yml
- .expeditor/publish-release-notes.sh
Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
Add seamless release notes expeditor config to Supermarket.
> Add seamless release notes

- .expeditor/config.yml
Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
Publish the release notes, then announce them.
> Looks like it's supposed to publish then announce

- src/supermarket/app/views/users/_sidebar.html.erb
- Added font awesome slack icon.
#2253
> Added font awesome slack icon in user profile

- .github/workflows/ctl-cookbook-testing.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- omnibus/config/projects/supermarket.rb
- src/supermarket/Gemfile
- src/supermarket/Gemfile.lock
upgraded chef infra version from 16.13 to 17.5
#1923
> upgraded chef infra version from 16.13 to 17.5

- omnibus/config/projects/supermarket.rb
> remove duplicate dependency "chef"

- src/supermarket/app/views/sessions/new.html.erb
- Updated login button text to Login with Chef Infra Server
> Updated "Login with Chef Server" text to "Login with Chef Infra Server"

- docs/supermarket-release-checklist.md
Added documentation for supermarket release checklist.
#2206
> supermarket release checklist documentation

- docs-chef-io/Makefile
Fix the Netlify build scripts
See #2373 & chef/chef-web-docs#3548
> Fix Netlify config

- src/supermarket/config/application.rb
> Revert "Changed rails autoloader version from 5.1 to 6.0"

- omnibus/cookbooks/omnibus-supermarket/templates/nginx.conf.erb
> Add permission policy for nginx to block camera and payment

- omnibus/Gemfile.lock
- src/supermarket/Gemfile.lock
Dependabot PRs fix
PR #2405 
PR #2406
> dependabot prs fix

- docs-chef-io/content/supermarket/config_rb_supermarket.md
- omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
- omnibus/cookbooks/omnibus-supermarket/templates/nginx.conf.erb
- Added force hsts header.
#2297
> Adding option to 'force-hsts' headers

- .github/workflows/unit.yml
> Remove simplecov step from unit github action

- .github/workflows/unit.yml
Fix simplecov error on forked repo PRs and dependabot PRs
#2430
> Fix simplecov error on forked repo PRs and dependabot PRs

- .github/workflows/docs-lint.yml
Adds spellcheck and markdownlint for documentation files.
> Documentation lints

- .github/workflows/brakeman-analysis.yml
> Don't run Brakeman on docs

- .github/workflows/ctl-cookbook-testing.yml
Exclude the docs from ctl tests
> Don't cookbook-ctl test docs

- .github/workflows/lint.yml
Don't run code tests on documentation
> Don't run code lints on docs

- docs-chef-io/netlify.toml
Bump Hugo to latest version. Changes are coming.
> Update hugo version 0.91.2

- omnibus/cookbooks/omnibus-supermarket/templates/nginx.conf.erb
The format changed on this header. Make sure we set the final form.
> Fix the Permissions-Policy header for the new format

- docs-chef-io/content/supermarket/install_supermarket.md
- omnibus/cookbooks/omnibus-supermarket/README.md
Make sure we point to the latest downloads site
> Update docs links to the downloads site

- README.md
- src/supermarket/engines/fieri/spec/models/contributing_file_worker_spec.rb
- src/supermarket/engines/fieri/spec/models/testing_file_worker_spec.rb
- src/supermarket/engines/fieri/spec/models/version_tag_worker_spec.rb
> Fix the capitalization of GitHub

- .github/workflows/unit.yml
- src/supermarket/app/helpers/custom_url_helper.rb
- src/supermarket/app/views/cookbooks/directory.html.erb
- src/supermarket/spec/views/cookbooks/directory.html.erb_spec.rb
Signed-off-by: saghoshprogress <saghosh@progress.com>
> WIP Updated the workstation download url

- src/supermarket/engines/fieri/Gemfile.lock
> Update Fieri deps in the gemfile.lock

- src/supermarket/engines/fieri/Rakefile
- src/supermarket/engines/fieri/app/controllers/fieri/jobs_controller.rb
- src/supermarket/engines/fieri/app/models/contributing_file_worker.rb
- src/supermarket/engines/fieri/app/models/source_repo_worker.rb
- src/supermarket/engines/fieri/bin/rails
- src/supermarket/engines/fieri/fieri.gemspec
- src/supermarket/engines/fieri/spec/dummy/Rakefile
- src/supermarket/engines/fieri/spec/dummy/config.ru
- src/supermarket/engines/fieri/spec/dummy/config/application.rb
- src/supermarket/engines/fieri/spec/dummy/config/boot.rb
- src/supermarket/engines/fieri/spec/rails_helper.rb
> Resolve Fieri chefstyle warnings

- .expeditor/announce-release.sh
Make sure we announce with the latest URL
> Update the announcement script for new downloads site

- src/supermarket/app/helpers/custom_url_helper.rb
- src/supermarket/app/views/layouts/application.html.erb
- src/supermarket/spec/helpers/custom_url_helper_spec.rb
> Update docs and blog links

- docs-chef-io/content/supermarket/_index.md
New image that matches the site's appearance in 2022.
> Use the new PNG supermarket image

- .github/workflows/docs-lint.yml
Change the `docs-lint` GitHub action to run on the docs files.
https://github.com/chef/chef-web-docs/issues/2906
> Fix spellcheck

- docs-chef-io/content/supermarket/_index.md
- docs-chef-io/cspell.json
The spell action isn't respecting the docs dictionary. Hopefully, this configuration will help.
> Add cspell.json

- src/supermarket/config/routes.rb
- src/supermarket/spec/routing/universe_routes_spec.rb
- Added universe route in api/v1/.
- Added spec for the changes.
#1807
> Added universe end_point in api/v1/

- .github/workflows/docs-lint.yml
> Use central cspell config

- dev-docs/supermarket-release-process.md
- Release process doc
Fixes https://github.com/chef/supermarket/issues/2073
> Release process doc

- dev-docs/supermarket-release-checklist.md
Signed-off-by: Dheeraj Singh Dubey <dhsingh@progress.com>
-- Updated some missing settings those are required while testing manual builds.
> Update release checklist doc

- docs-chef-io/content/supermarket/supermarket_upgrade.md
All docs changes for supermarket release version 5.0
> Docs update for upgrading to version 5.0

- docs-chef-io/Makefile
Updates the docs makefile to handle changes made to chef-web-docs.
> Update docs makefile

- src/supermarket/package-lock.json
- src/supermarket/package.json
Signed-off-by: pratixha <pratiksha.prajapati@msystechnologies.com>
"karma": "~6.3.16",
"karma-coffee-preprocessor": "^1.0.1",
"karma-mocha": "^2.0.1",
"karma-osx-reporter": "^0.2.1",
"karma-phantomjs-launcher": "^1.0.4",
"karma-requirejs": "^1.1.0",
"karma-spec-reporter": "^0.0.33",
> karma devDependencies updated

- omnibus/Gemfile.lock
- src/supermarket/Gemfile.lock
- src/supermarket/engines/fieri/Gemfile.lock
Signed-off-by: pratixha <pratiksha.prajapati@msystechnologies.com>
#2686 
#2687 
#2688 
#2689 
> Combined dependabot PRs

- .expeditor/config.yml
- src/supermarket/config/initializers/content_security_policy.rb
Fix CSP for allowing google-analytics script
> Fix CSP for allowing google-analytics script

- src/supermarket/package-lock.json
- src/supermarket/package.json
Signed-off-by: pratixha <pratiksha.prajapati@msystechnologies.com>
It will fix 3 security vulnerabilities :-
Total 16 vulnerabilities (4 moderate, 9 high, 3 critical)
https://snyk.io/vuln/npm:sprockets-chain@0.0.16
> Fixed security vulnerabilities

- docs-chef-io/content/supermarket/supermarket_backup_restore.md
PG restore command correced in the doc
Source PR: https://github.com/chef/supermarket/pull/2745
> PG restore command fixed in the docs

- .expeditor/publish-release-notes.sh
Update the publish release file
> Updated the publish release file

- docs-chef-io/content/supermarket/install_supermarket.md
- docs-chef-io/content/supermarket/supermarket_upgrade.md
Replace links to Chef downloads.
https://chefio.atlassian.net/browse/CHEF-3473
> CHEF-3473 Update download links

- docs-chef-io/content/supermarket/ctl_supermarket.md
- docs-chef-io/content/supermarket/supermarket_api.md
Cleanup a couple more files.
#3141
> CHEF-4515 Cleanup a couple more files

- docs-chef-io/content/supermarket/install_supermarket.md
One more file. Hopefully this is the last one.
#3144
#3141
> CHEF-4515 Cleanup one more

- omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
Signed-off-by: ayush-billore <ayush.billore@progress.com>
> Fix default values of feature flags

- docs-chef-io/.gitignore
- docs-chef-io/Makefile
- docs-chef-io/go.mod
Update how Netlify builds docs previews
https://github.com/chef/chef-web-docs/pull/4255
https://chefio.atlassian.net/browse/CHEF-11081
> Update Netlify builds

- .expeditor/release.omnibus.yml
- omnibus/config/projects/supermarket.rb
- omnibus/omnibus.rb
Extend support of supermarket for RHEL 9 platform
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EdF6xF8Db2RHrY03bUx2ZtQBoQ3SInBfVAGxoEfNbKZP2A?e=WHv6u7
> Added support for RHEL-9

- docs-chef-io/content/supermarket/supermarket_upgrade.md
This edits the docs content in #3291
https://progresssoftware.atlassian.net/browse/CHEF-21841
> Editing docs in #3291
