config/locales/en.yml

Change the unsubscription messages to not use the word "destroy", because in this context it sounds like Supermarket `rm -rf`'d the repo.

Remove frightening destruction message

---

app/views/application/_appheader.html.erb

:fork_and_knife: 
Here's my stab at addressing @juliandunn's comment in #975. Notably, it transitions from a noun-y link to a verb-y link, like the others in the menu.

Clarify text in the link to Curry's repositories

---

README.md

Removes Vagrant dev setup instructions that haven't worked for some time.  The local dev setup instructions do work.

removing non-working vagrant set up instructions

---

config/environments/production.rb

Make the log_level configurable.
Per @smith we should also look at https://github.com/heroku/rails_stdout_logging
Once configurable logging is implemented, we should update omnibus-supermarket to make it configurable

Make log level configurable

---

README.md

Noticed that this link was giving 404 so changed it to point to opscode-cookbooks/supermarket instead.

Update link to supermarket cookbook in README.md

---

db/seeds.rb

I've been working with cookbook search based on supported platforms. To experiment with it I
added some platforms and dependencies to seed.rb. I thought that it might be useful in
general to have those in development env database so I open this PR for discussion. 
This PR adds some platforms to 3 cookbooks and makes all default cookbooks depend on apt.
@nellshamrell - I didn't open issue about this since I already had this start to offer.

Add some platforms and dependencies to seed.rb

---

db/seeds.rb

I forgot commas to platform names in seed.rb. We probably don't want them there. Sorry about that :smile:

Remove commas from platform names in seed.rb

---

app/views/application/_announcement_banner.html.erb

The Announcement banner is currently not active on public Supermarket.  After this is deployed, it needs to be activated through rails console.  
ROLLOUT.enable(:announcement)  (I think, will verify) needs to be run from console.

Updating Announcements Banner

---

app/assets/stylesheets/cookbooks/search.scss
app/views/application/_search.html.erb

I noticed that my last PR #1028 had an unintentional side effect. When you use supermarket on a large screen it fails to keep search-bar as wide as the whole page. So here is a fix for that.

Make search-bar as wide as the whole page when using xlarge screen

---

Gemfile

Also update `:github` lines in the Gemfile to use https instead.

Remove the Ruby 2.1.3 pin from the Gemfile, because we're already pinning it in omnibus-supermarket

---

app/models/universe.rb
spec/api/universe_spec.rb

cookbook autodependencies are bad to feed into depsolvers.  cookbooks
all automatically are dependencies of themselves, but some people still
do:
name 'foo'
depends 'foo'
what this can actually do is create depsolver loops where all the
versions of a cookbook create dependency loops which satsify this
constraint and make the depsolver work much harder than it should.
this patch just stops supermarket from publishing this information out
and starts to stop the pain.
additionally, there should be a migration added to clean these up and
there should be filtering on the input side.  knife and the chef server
also need to clean them up as well on the client and server side.
at the same time, though, we need to not completely break old cookbooks,
so we'll probably be stuck with maintaining …

stop rendering autodependencies

---

app/assets/stylesheets/simple_listing.scss
app/views/cookbooks/available_for_adoption.html.erb

- Use CSS3 built-in method for selecting list pattern children
- Remove one level of `li` nesting
> As a Supermarket Viewer
When viewing the [Adoption Cookbooks page](https://supermarket.chef.io/available_for_adoption)
Then I want to be able to visually differentiate quickly between lines.
I tried to achieve this in two methods. This PR and another here: https://github.com/chef/supermarket/compare/chef:master...miketheman:scss_simple_listing
I think this method is the "cleaner" one, as it cleans up one level of LI nesting, and uses a [built-in selector](http://www.w3schools.com/cssref/sel_nth-child.asp) instead of using Rails logic to tag items when rendering.
The end result of both methods is the same, appears like so:
I wasn't certain which coloring to use, so I chose one that seemed …

add zebra striping to adoption list

---

lib/tasks/setup.rake

`rake setup:deps` validates that the correct minimum versions are
installed and are running.
/cc: @nellshamrell @kirtfitzpatrick

add rake tasks to verify development/test env

---

app/services/make_user_admin.rb
config/locales/en.yml
lib/tasks/user.rake
spec/services/make_user_admin_spec.rb

This adds a rake task users can use to promote an existing user to Admin.
This is intended to be called by a supermarket-ctl command, which I will add to the [omnibus-supermarket](https://github.com/chef/omnibus-supermarket) repo.
I will update this when the pull request to supermarket-ctl is also ready to go.  Once that is added, this should be good to merge.

Make user admin task

---

app/views/application/_announcement_banner.html.erb

The gitter channel was decom'd back in May.  Removing the reference to it from the current announcement banner.

remove gitter reference from announcement banner

---

docs/CONFIGURING.md

There is now a supermarket-ctl command to create the initial admin user for a Supermarket install, this updates the documentation.

changing documentation around making an admin user

---

app/authorizers/cookbook_authorizer.rb
spec/authorizers/cookbook_authorizer_spec.rb

This means that I can add myself to chef cookbooks as an admin and
then can upload cookbooks.  Otherwise I have to pester Sean even
though I'm an "admin", although I can issue a transfer request but
that is going to be even more annoying.

add ability of admins to add collaborators

---

config/locales/en.yml

Fix small typo in ICLA duplicate_signature message

---

app/views/profile/edit.html.erb

Noticed a couple of broken links while trying to configure my machine to share cookbooks to public Supermarket.

Add missing protocol to links in Manage Profile

---

docs/CONFIGURING.md

corrects typo in docs around supermarket-ctl make-admin command

---

app/views/profile/edit.html.erb

It seems we missed a closing `</a>` instead of `<a>`

Missed a closing tag

---

CONTRIBUTING.md

Such a little tweak, but names the ICLA as such before talking about a thing called "ICLA" later when linking to more info about signing.

Introduce the ICLA before mentioning the ICLA.

---

app/models/ccla_signature.rb
app/models/icla_signature.rb
db/seeds.rb
spec/models/ccla_signature_spec.rb
spec/models/icla_signature_spec.rb
spec/models/organization_spec.rb

Fixes #1132 
Adds a loop to seeds.rb creating a bunch of users for the existing "create signatures" logic to use.
In the process, discovered that the CCLA and ICLA tests were relying on spec let ordering for logic around `signed_at`. Reordered tests, instantiating the more recent signature first. This revealed that the `signed_at` passed in to the factory was being overwritten by the `before_create` callback in both signature classes. Updated the callback to use a set value or default to `Time.now` as before.

Fix signer creation in seeds

---

docs/CONFIGURING.md

This adds in the minimum recommended specifications for a server to run a private Supermarket.
Fix for #1133

adds recommended minimum specifications for a supermarket server

---

app/models/ccla_signature.rb
app/models/cla_report.rb
app/models/cookbook.rb
app/models/icla_signature.rb
app/views/tools/index.atom.builder
lib/supermarket/health.rb
spec/support/api_spec_helpers.rb
spec/support/omni_auth_control.rb
spec/workers/oauth_token_refresh_schedule_worker_spec.rb
spec/workers/oauth_token_refresh_worker_spec.rb

Per a few resources' recommendations[1], calls for current time in a Rails
app should be to `Time.current` not `Time.now`.
[1] Resources:
* http://rails-bestpractices.com/posts/2014/10/22/use-time-zone-now-instead-of-time-now/
* http://danilenko.org/2012/7/6/rails_timezones/
* http://winstonyw.com/2014/03/03/time_now_vs_time_zone_now/
Addresses issue #1139

Change all calls to Time.now into Time.current

---

app/controllers/collaborators_controller.rb
app/controllers/concerns/collaborator_processing.rb
spec/controllers/concerns/collaborator_processing_spec.rb

This refactors the logic around adding a collaborator out of the collaborator controller into a concern.  I realized this refactor was needed during the process of coding the groups feature for Supermarket.  When that feature is launched, we will need the ability to add collaborators (and all the checking that is part of that process) to be accessible from more places than just one action in the collaborator controller.  Rather than repeat the code in multiple controllers, I refactored it into the concern you see here.

Add collaborator refactor 2

---

app/controllers/collaborators_controller.rb
app/controllers/concerns/collaborator_processing.rb
spec/controllers/collaborators_controller_spec.rb
spec/controllers/concerns/collaborator_processing_spec.rb

This is similar to #1146, but it refactors removing a collaborator into the shared controller concern.  This continues to lay the foundation for the groups feature, which requires the ability to remove a collaborator from multiple controllers.  The reason this is in a controller concern, rather than a service object, is that Pundit (our authorization service) requires access to controller methods such as current_user.

refactors removing a collaborator logic into a shared controller concern

---

MAINTAINERS.md
MAINTAINERS.toml

Also, changed capitalization of 'GitHub' key for people so the markdown
version would generate links to GitHub accounts correctly.
Hopefully @nathenharvey and @nellshamrell don't veto me!

Add Robb Kidd to Supermarket maintainers

---

.travis.yml
Gemfile
Gemfile.lock
lib/tasks/spec/all.rake

Pin bundler-audit to a version with `check --update` option. This
unreleased version lets us perform an update of the vulnerability
database during the check.

Add bundle-audit to CI test suite

---

lib/active_model/validations/chef_version_constraint_validator.rb
spec/lib/active_model/validations/chef_version_constraint_validator_spec.rb
spec/models/cookbook_dependency_spec.rb
spec/models/supported_platform_spec.rb

The default message was vague for an invalid dependency or platform version
constraint. For example:
```
Stove::Cli | >>>> The Chef Server did not understand the request because it was malformed.
{ "error_code"=>"INVALID_DATA",
"error_messages"=>["Version constraint is not a valid Chef version constraint"]
}
```
The error above did not contain enough information for a cookbook author to determine which of the versions they had declared in metadata was invalid.
This change includes the exception class and detail from the original exception thrown about what is invalid about the data given. With this change, the error above would appear as:
```
Stove::Cli | >>>> The Chef Server did not understand the request because it was malformed.
{ "error_code"=>"INVALID_DATA", …
```

Add detail from exception thrown during version validation

---

.travis.yml

Use the apt add-on to remove the need for sudo
Use use the actual libxslt package vs. the virtual that isn't approved
by travis

Use container infrastructure in travis

---

.travis.yml
Gemfile.lock
README.md
spec/controllers/api/v1/cookbook_versions_controller_spec.rb

Opting for a minor version upgrade to Ruby 2.2.3 instead of patch upgrade to 2.1.7 because of [build trouble](https://github.com/chef/supermarket/pull/1155#issuecomment-156473682).
This will probably be a multi-part process:

Upgrade to Ruby 2.2.3

---

.travis.yml
README.md

Fixes #1183 by reverting back to 2.1 series.

Bring Ruby version back in to 2.1.x

---

app/views/layouts/application.html.erb
spec/vcr_cassettes/sitemap_refresh_worker.yml
spec/workers/sitemap_refresh_worker_spec.rb

With some judicious application of firewall rules, hunted down the places where tests were still making calls to 3rd parties.
* Wrapped the search engine ping for the sitemap update in a VCR cassette.
* Wrapped the header CDN inclusions such that they are not loaded in the test environment
Fixes #1187

Guard 3rd party calls in test

---

.travis.yml
db/migrate/20160109212307_enable_pg_extensions.rb
db/schema.rb

These extensions are already included in the schema. But [pg_trgm was added directly to schema.rb](https://github.com/chef/supermarket/commit/99d7990d85e36821c57d43d2861316f46c0407de) leaving newly migrated databases (e.g. dev and test) without the extensions being included in the resultant post-migration schema.rb.
plpgsql is included from the PG adapter on platforms that need it, so it is not included directly in this migration.
pg_trgrm is needed for PG search to work.

Add a migration to ensure current DB extensions are enabled.

---

app/controllers/ccla_signatures_controller.rb

We have a lot of wasted whitespace on this page and since we lack a search box it takes a long time to find a user / company.  This would reduce the time spent searching the pages.

Default the CLA pages to 50 companies / users per page

---

.travis.yml

* Enables Slack notifications of test builds to team's room
* Leaves *enabled* testing of new commits on PRs
* _Disables_ testing of pushes to any branch but `master`; prevents the double builds we've been seeing for every push to a PR
Also:
* Removed gitter.im webhook for a room that doesn't appear to be in use.
* Travis command line client really wanted to reformat the YAML.

Add Slack notifications for test builds

---

app/views/cookbooks/_main.html.erb
db/seeds.rb
spec/features/cookbook_view_spec.rb

Fixes #1159
* Update development seeds to include 2 cookbook versions
* Even versions will depend on apt cookbook, odds on yum
* Give supported platforms a different version per version of cookbook, too

Fix display of dependencies for a cookbook version other than latest

---

Guardfile

dots when running all, spec text when focused on a change
Example:
**Guard starting up, running all specs and rubocop**
```
» be guard
16:22:14 - INFO - Guard::RSpec is running
16:22:14 - INFO - Running all specs
Run options: include {:focus=>true}
All examples were filtered out; ignoring {:focus=>true}
Randomized with seed 55593
......................................................................................................................................................................
......................................................................................................................................................................
...................................................................................................................................... …
```

Adjust guard-rspec's output

---

app/assets/stylesheets/contribute.scss
app/controllers/ccla_signatures_controller.rb
app/controllers/contributors_controller.rb
app/controllers/icla_signatures_controller.rb
app/helpers/application_helper.rb
app/models/icla_signature.rb
app/models/user.rb
app/views/application/_contributors_list_heading.html.erb
app/views/contributors/index.html.erb
spec/controllers/ccla_signatures_controller_spec.rb
spec/controllers/contributors_controller_spec.rb
spec/controllers/icla_signatures_controller_spec.rb
spec/features/contributors_search_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/icla_signature_spec.rb
spec/models/user_spec.rb

Add contributor search

---

app/controllers/api/v1/cookbooks_controller.rb
spec/controllers/api/v1/cookbooks_controller_spec.rb
spec/factories/cookbook_version.rb

Closes #1228.
Can filter by platforms in the API.
e.g.
https://supermarket.chef.io/api/v1/cookbooks?platforms[]=mac_os_x

Add filter by platform to cookbook index API [1228]

---

app/assets/javascripts/cookbookDeprecate.js
app/controllers/cookbooks_controller.rb
app/mailers/cookbook_mailer.rb
app/models/cookbook.rb
app/views/cookbook_mailer/cookbook_deprecated_email.html.erb
app/views/cookbook_mailer/cookbook_deprecated_email.text.erb
app/views/cookbooks/_manage_cookbook.html.erb
config/locales/en.yml
spec/controllers/cookbooks_controller_spec.rb
spec/features/cookbook_deprecation_spec.rb
spec/models/cookbook_spec.rb
spec/workers/cookbook_deprecated_notifier_spec.rb

* Turn off JS to allow form to be submitted without content in the text
field
* Turn the requirement for a cookbook->replacement parameter into a permit
so that form can be submitted without a name
* Move the replacement cookbook lookup into the Cookbook.deprecate method
* Update deprecation messaging to not assume there is a replacement
cookbook
Closes #1223

Allow cookbook deprecations without a replacement cookbook

---

app/assets/stylesheets/cookbooks/show.scss
app/views/cookbooks/_main.html.erb
app/views/cookbooks/_manage_cookbook.html.erb
spec/features/cookbook_undeprecation_spec.rb

Reads better and doesn't require the cookbook author to say all this in a
README update in a new cookbook release (even though that's still a good
thing to do.)
:wink:

Revised the copy of deprecation form and display banners

---

omnibus/package-scripts/supermarket/postrm

During an upgrade, RPM runs the old package's post-uninstall script as the
last step. Replicate the solution from the same problem with Chef and Chef
Server (https://tickets.opscode.com/browse/CHEF-3022).
Fixes #1265

Update postrm script to not rm symlinks during upgrade on RHELish systems

---

omnibus/config/projects/supermarket.rb
omnibus/config/software/supermarket-cookbooks.rb
omnibus/config/software/supermarket-ctl.rb
omnibus/config/software/supermarket.rb

Makes the omnibus packager happier to have licensing info for the project.

Add license info to project and software definitions

---

omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/console.rb
src/supermarket/Gemfile
src/supermarket/Gemfile.lock

We upgraded omnibus-software to a version whose Ruby no longer had readline
compiled within. This adds the rb-readline gem to provide the same functionality
with only Ruby and UNIX commands.
Needed to update the PATH in the -ctl console command so that utilities like
stty required by rb-readline would be available.
Fixes #1271

Use rb-readline gem to fix the Rails console

---

src/supermarket/db/seeds.rb

The README stayed at the root of the repo, so the seeds file needs the new path to it for faker cookbooks in development.

Fix seeds with new location of README

---

omnibus/Gemfile.lock
omnibus/config/software/supermarket-cookbooks.rb

This PR picks up the latest version of omnibus and omnibus-software which contains the required license information and the logic to publish this information to artifactory. After this change our download pages will be able to be updated to display the project specific license for supermarket.
/cc: @chef/engineering-services @chef/supermarket

Updates for publishing licensing information

---

omnibus/.kitchen.yml

I've been manually adding Ubuntu 12.04 to the .kitchen.yml and see no reason not to include it in the .kitchen.yml stored in source code

adds ubuntu 12.04 to the list of kitchens

---

src/supermarket/app/controllers/cookbook_versions_controller.rb
src/supermarket/app/models/cookbook_version.rb
src/supermarket/app/workers/fieri_notify_worker.rb
src/supermarket/config/routes.rb
src/supermarket/spec/api/cookbook_evaluation_results_spec.rb
src/supermarket/spec/controllers/cookbook_versions_controller_spec.rb
src/supermarket/spec/models/cookbook_version_spec.rb
src/supermarket/spec/workers/fieri_notify_worker_spec.rb

This alters the cookbook_version.tarball.url to point to the correct location when a Supermarket is storing its cookbook on disc.
This also corrects a typo in one of our routes "cookbook_verisons" (switched i and s) is now "cookbook_versions."  I have left the old route in with a note in case anyone is still using it.  I have verified that both urls work with a live Private Supermarket and Fieri instance.

Fieri use with on disk cookbooks

---

.travis.yml
src/supermarket/lib/tasks/spec/all.rake
src/supermarket/package.json

Upgrade some karma packages for running JS specs on Mac
New Travis-specific rake task for tests to run there.
* Removing `spec:javascripts` from the list to run at Travis as the one JS spec
the project has tests a div flash fade which isn't worth all the chattiness
of the npm module install.
Fixes #1282

Fix JS specs

---

src/supermarket/app/controllers/cookbooks_controller.rb
src/supermarket/app/models/cookbook.rb
src/supermarket/spec/controllers/cookbooks_controller_spec.rb

Rather than any change in the cookbook itself. 
Fixes #1244

"Recently Updated" cookbooks list now refers to list of recently shipped new versions

---

src/supermarket/app/views/cookbooks/_main.html.erb

Fixes #1026
Note: I was able to replicate part of the problem locally and believe the issue was with the `data-equalizer-watch` foundation class, documented [here](http://foundation.zurb.com/sites/docs/v/5.5.3/components/equalizer.html). I removed the class and the problem went away locally.

Fix for disappearing browser when clicking a cookbook's CHANGELOG tab

---

omnibus/config/software/supermarket-cookbooks.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/serverspec/recipes/default_spec.rb

Previously running reconfigure would yield many WARN-level messages
because the cache was embedded in the cookbook directory.  This moves
the cache to a more appropriate directory and cleans up the old cache
dir.
Sample warnings:
```
[2016-05-12T14:02:32+00:00] WARN: Cookbook 'local-mode-cache' is empty or entirely chefignored at /opt/supermarket/embedded/cookbooks/local-mode-cache
[2016-05-12T14:02:32+00:00] WARN: Cookbook 'local-mode-cache' is empty or entirely chefignored at /opt/supermarket/embedded/cookbooks/local-mode-cache
[2016-05-12T14:02:32+00:00] WARN: Cookbook 'local-mode-cache' is empty or entirely chefignored at /opt/supermarket/embedded/cookbooks/local-mode-cache
[2016-05-12T14:02:32+00:00] WARN: Cookbook 'local-mode-cache' is empty or entirely chefignored at …
```

Move the cache_path into the omnibus var dir to avoid warnings

---

src/supermarket/config/initializers/paperclip.rb

This temporarily fixes #1301
What happened was, when we deployed #1281, we started seeing errors from berks.  This was due to the fact that our prod S3 bucket has "." in the name, which cannot be used with the path style.  #1307 begins to address this, but that PR needs some additional work.  In order to make this shippable for now, I am reversing the s3 url style change.

reverts changing paperclip to use path urls

---

src/supermarket/app/views/cookbooks/_main.html.erb

Changes Foodcritic tab to Quality tab and removes icon indicating whether a cookbook version has passed food critic from the Quality tab. 
Fixes #1309

Changes Foodcritic tab to Quality tab

---

src/supermarket/app/controllers/transfer_ownership_controller.rb
src/supermarket/app/mailers/cookbook_mailer.rb
src/supermarket/app/models/cookbook.rb
src/supermarket/app/models/ownership_transfer_request.rb
src/supermarket/app/views/cookbooks/_manage_cookbook.html.erb
src/supermarket/db/migrate/20160511224519_add_add_owner_as_collaborator_attribute_to_ownership_transfer_request.rb
src/supermarket/db/schema.rb
src/supermarket/spec/controllers/transfer_ownership_controller_spec.rb
src/supermarket/spec/models/cookbook_spec.rb
src/supermarket/spec/models/ownership_transfer_request_spec.rb

Fixes #1224
Adds checkbox in workflow for transferring ownership that gives option to keep current user on as a collaborator, streamlines the logic action for both admins/collaborators and non-admins/collaborators.

Option to add current owner as a collaborators when transfering ownership

---

omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/console.rb
omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/helpers/ctl_command_helper.rb
omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/helpers/user_check_helper.rb
omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/make-admin.rb
omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/test.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/serverspec/ctl-commands/console_spec.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/serverspec/ctl-commands/make_admin_spec.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/serverspec/ctl-commands/test_spec.rb

Fixes #1314
Calling sudo within the ctl command conflicts with a host configuration whose sudoers requires a TTY.
This removes the call to sudo from within the command and displays an error to the user if the ctl
command is being run as an OS user other than the 'supermarket' service user.

WIP: Add a guard to Supermarket-specific ctl commands to require being run as supermarket service user

---

omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/test.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/serverspec/ctl-commands/test_spec.rb

It can run as root. And currently does in the CI pipeline, so let's let it.
Makes the CI tests happier.

Remove as-supermarket-user guard from `-ctl test` command

---

src/supermarket/app/views/cookbooks/_main.html.erb

Fixes #1336 
foodcritic_failure will be nil if fieri hasn't posted back results. If
fieri has posted results, foodcritic_failure will be true or false. false
means success (argh, double negatives!), but false is also not `present?`
and so the test for presence fails and the view thinks there are no
results.
This flips the test from `present?` to `nil?` and flips the if/else
clauses. This was the smallest change to fix the display of foodcritic
success.
Future TODOs:
- extract the quality section of this partial to its own partial for focused testing with a view spec
- remove the foodcritic_failure column altogether and have fieri post feedback—positive or negative—for this view to display more simply

Fix Quality tab not displaying successful foodcritic feedback.

---

src/fieri/app/models/cookbook_artifact.rb

This should fix fieri's CookbookWorker failing with encoding errors when binary files (like other tarballs) are included in a cookbook artifact.

Untar all files in a cookbook artifact as binary to avoid encoding issues

---

omnibus/.kitchen.yml
omnibus/Gemfile.lock
omnibus/cookbooks/omnibus-supermarket/.kitchen.yml
omnibus/cookbooks/omnibus-supermarket/templates/default/sv-rails-run.erb
omnibus/cookbooks/omnibus-supermarket/templates/default/sv-sidekiq-run.erb

Closes #1351 
Also:
* removes Ubuntu 10.04 from kitchen configs now that it is unsupported
* needed to include `HOME` environment variable in startup scripts for Ruby services to make rbreadline happy.

Update omnibus & omnibus-software for new version of OpenSSL

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock

Fixes #1352 
Sidetiq 0.7.0 has resolved the celluloid problem after Sidekiq 3.4.2.
This appears to fix a stack level too deep error when attempting
CookbookWorker.perform_async

Upgrade Sidekiq & Sidetiq to resolve stack too deep error

---

omnibus/cookbooks/omnibus-supermarket/.kitchen.yml
omnibus/cookbooks/omnibus-supermarket/Berksfile
omnibus/cookbooks/omnibus-supermarket/Berksfile.lock

Bumped versions of enterprise and sysctl cookbooks for systemd support.
Passes tests locally on ubuntu 16.04.

[JEX-169] Support use of systemd on ubuntu 16.04

---

omnibus/cookbooks/omnibus-supermarket/recipes/config.rb

Create log and var directory recursively in case parent directories don't exist.
Without these options, setting the log and var directories to non-default locations will fail randomly due to missing parents. Furthermore, the cookbook will (try to) make subdirectories of these locations without having ensured they exist.
```
[2016-07-01T20:22:58+00:00] INFO: Processing directory[/data/supermarket/log/sidekiq] action create (omnibus-supermarket::sidekiq line 20)
================================================================================
Error executing action `create` on resource 'directory[/data/supermarket/log/sidekiq]'
================================================================================
Chef::Exceptions::EnclosingDirectoryDoesNotExist …
```

Create the log directory to avoid failures which assume it's created

---

omnibus/cookbooks/omnibus-supermarket/recipes/database.rb

Our calls to `bundle exec` in the omnibus install need to have a HOME set because of an updated [rb-readline that requires an `ENV['HOME']` to be present](https://github.com/ConnorAtherton/rb-readline/issues/8). This is related to 28344e92c243974c991093474d90b64a7fe37b72, where a HOME was added to the runit startup scripts for rails and sidekiq. This is the only other `bundle exec` in the omnibus cookbook and so it needs a HOME, too.
Presumably fixes chef-cookbooks/supermarket-omnibus-cookbook#41, but we're currently lacking an automated reproduction of the problem and test of the fix.

Add a HOME to db migrate command in omnibus

---

src/supermarket/app/controllers/cookbooks_controller.rb
src/supermarket/app/mailers/adoption_mailer.rb
src/supermarket/app/views/adoption_mailer/follower_email.html.erb
src/supermarket/app/views/adoption_mailer/follower_email.text.erb
src/supermarket/spec/controllers/cookbooks_controller_spec.rb

Partially fixes #1184. This is a checked out branch separate from `master/adoption_process` for clarity of purpose. Another pull request will address the visibility of adoption on timelines. This is separate because the second part of the issue requires more attention and possible database migration.

Adoption Email Notice to Followers

---

src/supermarket/app/controllers/api/v1/cookbook_versions_controller.rb

Use the [`Cookbook.with_name`](https://github.com/chef/supermarket/blob/master/src/supermarket/app/models/cookbook.rb#L20-L24) scope to handle downcasing the cookbook name to find. Otherwise, the chained methods fail for cookbooks whose names contain capitals
when fieri posts results.
```
NoMethodError: undefined method `cookbook_versions' for nil:NilClass
```

Switch to using with_name scope to handle downcasing incoming cookbook names

---

src/fieri/app/models/foodcritic_worker.rb
src/fieri/spec/models/foodcritic_worker_spec.rb

Added test to confirm POST response was successful. Logs the error if not.
Based on the work in #1377 
Fixes #1327

Log foodcritic postback errors from fieri to supermarket

---

src/supermarket/app/views/cookbooks/_main.html.erb

Avoid a redirect and help the right URL get to the top in Google search results

Use the new Foodcritic URL

---

src/fieri/config/locales/en.yml
src/fieri/spec/models/collaborator_worker_spec.rb

We're mixing up plural vs. singular in the wording

Consistent naming

---

omnibus/cookbooks/omnibus-supermarket/.kitchen.yml
omnibus/cookbooks/omnibus-supermarket/recipes/cookbook_test.rb

Previously, the exact file path to a package file had to be set
for a version. Sadly, for RHEL, that file path includes the platform
version (e.g. el6 vs el7). This updates the kitchen config and test
recipe to only require a version number for the package to be tested
and computes the file path.
package_path's default is based on the kitchen config's
synced_folders.
Note, you'll still need to have a build for a particular platform
stowed in omnibus/pkg prior to running kitchen for the package to
be available within the TK machine.

Allow omnibus test-kitchen tests to run in parallel

---

.delivery/build_cookbook/recipes/_install_docker.rb
.delivery/build_cookbook/recipes/unit.rb

Check that the docker-compose we download is the one we expect with a checksum.
Also don't need to `uname` things because we only use 64-bit Linux builders for this pipeline.

Use remote_file instead of execute-n-curl

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
omnibus/cookbooks/omnibus-supermarket/templates/default/rails.nginx.conf.erb

Right now if you have a uppercase character in the hostname of your supermarket server and you try to access it thru http instead of https, an endless loop will occur because the regexp code on site-enabled/rails doesn't match the uppercase name. A simple * will fix regexp.
Fixes #1412

Case insensitive hostname

---

.delivery/build_cookbook/recipes/security.rb
.delivery/config.json

This is run during the Security phase of the Build stage because the team concluded that in general, the findings of gems that need to be updated is not a failure directly attributable the changes in a changeset. As such, the change to update gem versions should come in to the pipeline as a new change.

Check gem versions for known vulnerabilities during security phase.

---

omnibus/Gemfile.lock
omnibus/config/projects/supermarket.rb

[9.3.7](https://www.postgresql.org/docs/current/static/release-9-3-7.html):
* CVE-2015-3165: Avoid possible crash when client disconnects just
before the authentication timeout expires
* CVE-2015-3166: Improve detection of system-call failures and
information disclosure with out-of-memory situations and buffer
overflows.
* CVE-2015-3167: uniformly report decryption failures as "Wrong key or
corrupt data" to avoid the risk of aiding attackers in recovering keys
from other systems
[9.3.10](https://www.postgresql.org/docs/current/static/release-9-3-10.html):
* CVE-2015-5289: Guard against stack overflows in json parsing
* CVE-2015-5288: Fix contrib/pgcrypto to detect and report too-short
crypt() salts
[9.3.11](https://www.postgresql.org/docs/current/static/release-9-3-11.html):
* …

Upgrade PostgreSQL to 9.3.14

---

omnibus/Gemfile.lock
omnibus/config/projects/supermarket.rb

* OCSP Status Request extension unbounded memory growth (CVE-2016-6304)
* SSL_peek() hang on empty record (CVE-2016-6305)
* Missing CRL sanity check (CVE-2016-7052)
* SWEET32 Mitigation (CVE-2016-2183)
* OOB write in MDC2_Update() (CVE-2016-6303)
* Malformed SHA512 ticket DoS (CVE-2016-6302)
* OOB write in BN_bn2dec() (CVE-2016-2182)
* OOB read in TS_OBJ_print_bio() (CVE-2016-2180)
* Pointer arithmetic undefined behaviour (CVE-2016-2177)
* Constant time flag not preserved in DSA signing (CVE-2016-2178)
* DTLS buffered message DoS (CVE-2016-2179)
* DTLS replay protection DoS (CVE-2016-2181)
* Certificate message OOB reads (CVE-2016-6306)
* Excessive allocation of memory in tls_get_message_header() (CVE-2016-6307)
* Excessive allocation of memory in dtls1_preprocess_fragment() …

upgrade to OpenSSL 1.0.2j

---

omnibus/Gemfile.lock

[Curl version updated in omnibus-software](https://github.com/chef/omnibus-software/pull/758) to address several CVEs, so updating omnibus and omnibus-software in Supermarket project.
An omnibus build in dev environment with this Gemfile.lock produced:
```
$ grep curl /opt/supermarket/version-manifest.txt
curl                     7.51.0                                     sha256:65b5216a6fbfa72f547eb7706ca5902d7400db9868269017a8888aa91d87977c
```

Update omnibus gems for updated curl

---

src/supermarket/app/assets/stylesheets/cookbooks/search.scss

The toggle was butting up against the bottom of the search bar on mobile, this fixes that.
**Before:**
**After:** ✨

Generally simplify the advanced search toggle styles and make cute

---

src/supermarket/app/controllers/api/v1/tools_controller.rb
src/supermarket/spec/api/tools_search_spec.rb

Updated the tools-search API endpoint to behave more like the UI search logic. 
* Adds a type parameter so that tool results can be filtered by tool type.
* Adds order parameter to specify ordering of results.
Fixes #1454

add type and order parameters to the tools API search endpoint

---

src/supermarket/app/models/metric_result.rb
src/supermarket/app/models/quality_metric.rb
src/supermarket/db/migrate/20161116191103_add_admin_only_to_quality_metrics.rb
src/supermarket/db/schema.rb
src/supermarket/db/seeds.rb

I'm still confused about why when running `db:migrate db:seeds` together in a single rake command that the `QualityMetric` creation in seeds didn't know about the new column created by the migration. But `reset_column_information` forces a refresh from the schema in the database and gets us past the error.
As a bonus ...
Fixes #1471 by adding a default value of `false` to the `admin_only` column on `QualityMetric` and disallows NULL values. @nellshamrell and I agreed it was safe to modify this migration because it had not yet been included in release of Supermarket, so not production or staging systems would have seen and executed the migration's previous state.
Bonus bonus: learned about [ActiveRecord's `merge()`](http://api.rubyonrails.org/classes/ActiveRecord/SpawnMethods.html#method-i- …

fix seeds not knowing about a column we just added in a migration

---

src/fieri/app/models/license_worker.rb

These are the strings that are accepted as license options in `chef generate cookbook -I <license>`. These short versions are also the strings that appear in the metadata of `chef generate`'d cookbooks. (See discussion on [1477](https://github.com/chef/supermarket/pull/1477#discussion_r90479895) about licenses in the generators.)
TODO/CONSIDER:

Include short versions of the open source license strings

---

CODE_OF_CONDUCT.md

Link to the Chef Community Guidelines.
Words lifted liberally from @nathenharvey's [reaffirmation of our beliefs](https://discourse.chef.io/t/reaffirming-the-chef-community-guidelines/9841).

add a reference to the Chef code of conduct

---

src/supermarket/app/views/api/v1/users/show.json.jbuilder
src/supermarket/app/views/ccla_signatures/contributors.html.erb
src/supermarket/app/views/icla_signatures/index.html.erb
src/supermarket/app/views/profile/edit.html.erb
src/supermarket/app/views/users/_sidebar.html.erb
src/supermarket/spec/api/user_show_spec.rb
src/supermarket/spec/features/edit_profile_spec.rb
src/supermarket/spec/views/api/v1/users/show.json.jbuilder_spec.rb

The Chef community does not use JIRA to track issues anymore, so asking
for and displaying a JIRA username is confusing.
Edit profile feature test changed to set the previously-untested Twitter
username which is still a field on the form.
Fixes #1484

stop displaying JIRA username

---

src/supermarket/app/views/profile/edit.html.erb

Labels will help a human know what these fields are when they come back
to this form months after adding values that replaced the placeholder
text.
Fixes #1485

include labels for profile form fields

---

src/supermarket/app/helpers/cookbook_versions_helper.rb
src/supermarket/app/views/cookbooks/_sidebar.html.erb
src/supermarket/spec/helpers/cookbook_versions_helper_spec.rb

Fixes #1379 
Here is what I have come up with for displaying the versions of Chef and Ohai that a cookbook version supports.  I welcome any input on the view, etc.
(I will squash the commits when this is finalized)

Add chef ohai

---

src/supermarket/app/views/api/v1/cookbook_versions/_cookbook_version.json.jbuilder
src/supermarket/spec/api/cookbook_version_spec.rb

Went with "published_at" based on created_at time.
Looks a bit like:
```json
{
"license": "blargle",
"tarball_file_size": 1698,
"version": "0.1.0",
"published_at": "2017-01-06T19:05:51Z",
"average_rating": null,
"cookbook": "http://localhost:3000/api/v1/cookbooks/blargle",
"file": "http://localhost:3000/api/v1/cookbooks/blargle/versions/0.1.0/download",
"quality_metrics": []
}
```
Closes #1515

include the published_at in API info for cookbook version

---

src/fieri/app/models/cookbook_artifact.rb
src/fieri/spec/models/cookbook_artifact_spec.rb

Fixes #1348
Based on the work of Logan McDonald in #1349
TODO Reach Goals:

omit the foodcritic working directory from metric feedback

---

src/supermarket/db/seeds.rb

A very small fix to the `Supported Platforms` quality metric seed introduced in [#1513](https://github.com/chef/supermarket/pull/1513/files#diff-8166a7994124585a9e368c1ae6847e34R34). A future refinement might be to iterate over a list of quality metric names and admin_only flags to reduce the likelihood of name mismatches between the `unless` guard and the `create!`.

correct pluralization in guard around create

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
src/supermarket/app/controllers/api/v1/cookbooks_controller.rb
src/supermarket/app/controllers/api/v1/tools_controller.rb
src/supermarket/app/controllers/api/v1_controller.rb
src/supermarket/spec/controllers/api/v1/cookbooks_controller_spec.rb
src/supermarket/spec/controllers/api/v1/tools_controller_spec.rb
src/supermarket/spec/controllers/api/v1_controller_spec.rb
src/supermarket/spec/support/shared_examples/v1_controller_shared.rb

Use `API_ITEM_LIMIT` environment variable to set the upper limit on the number of items to return for API requests to a Supermarket instance.
Defaults to the previously hard-coded value of 100 if the env var is not present. Also, the cookbook internal to the omnibus package has the same default set in the section of the attributes that get set as env vars.
Closes #1542

make the API item limit configurable

---

omnibus/.kitchen.yml
omnibus/Gemfile.lock
omnibus/cookbooks/omnibus-supermarket/.kitchen.yml

Omnibus builds were failing looking for the wrong license file within the nokogiri repo. Fix was in chef/omnibus-software#795 so updating our dependency to a version that includes that fix.
Also updates the CentOS boxes used in the omnibus kitchens to latest minor versions.

update to omnibus-software with nokogiri license check fix

---

src/supermarket/Gemfile
src/supermarket/config/initializers/datadog_tracer.rb

The tracer at the current version still tries to make connection attempts to the Datadog agent even when disabled. To disable those attempts and the log spam errors it generates, we'll only require the gem when we have enabled the tracer.
See datadog/dd-trace-rb#53 issue about the symptom.

really, really disable the datadog tracer

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
src/supermarket/config/initializers/sidekiq.rb

Adds an initializer for Sidekiq to configure which Redis instance to use for job queuing. Defaults to a common single `REDIS_URL` that will be shared with Rails caching and Rollout feature flag checking. Shared is less than ideal in high traffic production environments, so this adds the option to set a different Redis URL for Sidekiq.
https://github.com/mperham/sidekiq/wiki/Using-Redis#using-an-initializer
TODO:

make sidekiq optionally connect to an alternate redis

---

src/fieri/app/models/version_tag_worker.rb
src/fieri/spec/models/version_tag_worker_spec.rb

Sometimes metadata declares a repo that doesn't exist anymore. Catch that and return an empty list of tags to fail the version tag check.

add an exception handler for not finding a repo

---

src/supermarket/app/models/user.rb
src/supermarket/spec/models/user_spec.rb

Empty strings were sneaking through to produce `" "` for display which is not very useful.
Fixes #1576

update User#name to check for presence of first and last name

---

.delivery/build_cookbook/recipes/unit.rb
src/fieri/app/models/version_tag_worker.rb

Sometimes the `source_url` for a cookbook is an empty string, not a null. The `source_repo` metric will then return the empty string. So check for presence instead of nilness.

use present? to fail on empty strings

---

src/fieri/app/models/cookbook_artifact.rb

Zero length files aren't binary. They don't make much sense being
included in a cookbook, but they shouldn't cause the no binaries check
to fail.

don't treat empty files as binary

---

src/supermarket/config/initializers/datadog_tracer.rb

By default, leave `nil` which will allow the `env:` tag to be set by the Datadog agent configuration for the host. (crf. [new default in dd-trace-rb](https://github.com/DataDog/dd-trace-rb/pull/92/files#r110255719))

allow env: tag in DD agent to be customized

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
src/supermarket/config/initializers/paperclip.rb
src/supermarket/docs/CONFIGURING.md

Fixes #1301 
Before this is deployed, we will need to add this value to the supermarket vault
s3_domain_style: ':s3_path_url'

makes s3 bucket domain name style configurable

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb

Occasionally ohai fails to figure out a host's FQDN (e.g. `hostname -f` fails). Calling `.downcase` on `nil` causes much woe and gnashing of teeth. Therefore, we'll fallback to a host's hostname for the FQDN, much like [the workaround](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/d4b0fd8a0dcd5f01b89fab3140eb0f948a5d990c/resources/supermarket_server.rb#L26-L30) used in many wrapper cookbooks of making an entry in `/etc/hosts` for the hostname on the host's IP address if none is present.
Production Supermarkets are expected to provide an override for this value that matches a supplied SSL certificate. Defaults are mostly for development and test environments.
Fixes #1591

provide a fallback for when FQDN is indeterminate

---

src/fieri/Gemfile.lock
src/fieri/fieri.gemspec
src/supermarket/Gemfile.lock

Includes new critiques:
- Added FC069 to ensure standardized licenses are defined in metadata
- Added FC070 to detect invalid platform supports in metadata
- Added FC071 to ensure a LICENSE file is included with the cookbook

upgrade foodcritic to 10.3.1

---

src/fieri/config/locales/en.yml
src/supermarket/app/controllers/cookbook_versions_controller.rb
src/supermarket/app/controllers/cookbooks_controller.rb
src/supermarket/app/models/metric_result.rb

For now, we'll go alphabetical by name. A future may have the QM### identifier included and maybe sort by that ... but that's The Future.
Bonus'd in a correction to the GitHub URLs mentioned in some of the QM failure messages.

make quality metrics appear in a consistent order

---

src/supermarket/app/models/user.rb
src/supermarket/app/views/profile/edit.html.erb
src/supermarket/spec/models/user_spec.rb

If something has gone horribly awry with OC-ID and the oauth tango has not given Supermarket a public key to associate with the user, this stops the exception when attempting the produce a fingerprint for the key that's really nil.
If the key is missing, say so on the user's profile page with something to try to fix it.

prevent an exception if the user's public key is empty

---

src/fieri/app/models/foodcritic_worker.rb
src/fieri/app/models/no_binaries_worker.rb
src/fieri/spec/models/foodcritic_worker_spec.rb
src/fieri/spec/models/no_binaries_worker_spec.rb

These workers did not get updated with the new, shorter key names used for the params passed to the jobs.

fix fieri metrics that use artifact_url

---

omnibus/Gemfile.lock

Updates to a version of omnibus that automates populating the S3 cache. chef/omnibus#781

update omnibus to 5.6.1

---

.delivery/build_cookbook/libraries/helpers.rb
.delivery/build_cookbook/metadata.rb
.delivery/build_cookbook/recipes/deploy.rb
.delivery/build_cookbook/recipes/provision.rb
.travis.yml
cookbooks/supermarket-deploy/.gitignore
cookbooks/supermarket-deploy/Berksfile
cookbooks/supermarket-deploy/README.md
cookbooks/supermarket-deploy/attributes/default.rb
cookbooks/supermarket-deploy/chefignore
cookbooks/supermarket-deploy/libraries/helpers.rb
cookbooks/supermarket-deploy/metadata.rb
cookbooks/supermarket-deploy/recipes/default.rb
cookbooks/supermarket-deploy/recipes/omnibus_standalone.rb
scripts/install_terraform.sh
terraform/Makefile
terraform/acceptance/omnibus-standalone-inplace-upgrade.tf
terraform/acceptance/outputs.tf
terraform/acceptance/variables.tf
terraform/acceptance/vars/acceptance.tfvars
terraform/acceptance/vars/dev.tfvars
terraform/u-r-d/omnibus-standalone-inplace-upgrade.tf
terraform/u-r-d/outputs.tf
terraform/u-r-d/variables.tf
terraform/u-r-d/vars/delivered.tfvars
terraform/u-r-d/vars/dev.tfvars
terraform/u-r-d/vars/rehearsal.tfvars
terraform/u-r-d/vars/union.tfvars

* Add terraform to stand up AURD
* Add supermarket-deploy cookbook to configure AURD
* Update travis.yml to execute terraform lint tests
Ready to merge? View this change in Chef Automate and click the Approve button: https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/8650b71e-61c7-4cf6-a039-61812db76fc4

Add AURD Terraform + Cookbook

---

cookbooks/supermarket-deploy/Berksfile
cookbooks/supermarket-deploy/metadata.rb
cookbooks/supermarket-deploy/recipes/omnibus_standalone.rb

The unstable and current channels have artifact expiration, which means
that if the pipeline is not updated very frequently you can start having
CCR failures since the version is no longer available in that channel.
This leverages new code from cd-deploy to handle this case.
----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/59f5ae27-da1d-45d0-84df-227a1a0a5945) in Chef Automate and click the Approve button.

Add channel fallback support to deploy cookbook

---

.delivery/build_cookbook/Berksfile
.delivery/build_cookbook/metadata.rb
cookbooks/supermarket-deploy/Berksfile
cookbooks/supermarket-deploy/metadata.rb

----
Ready to merge? [View this change](https://automate.chef.co/e/chef/#/organizations/products/projects/supermarket/changes/b81e2193-d631-47b4-92c9-2662421aa46d) in Chef Automate and click the Approve button.

Put build-cookbook and supermarket-deploy back on master for helpers

---

src/supermarket/Gemfile.lock

mixlib-authentication 1.4.2 contains a fix for ordering signature
headers. Signatures generated from keys with large bit lengths would
themselves be long enough to spill over into 10 or more of the
X-Ops-Auth headers mixlib-authn expects and would misorder in earlier
versions of the library. See chef/mixlib-authentication#5 for gory
details.
Fixes #1656

update mixlib-authn to fix un/sharing with large keys

---

src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

Noted here that the omnibus build of Supermarket is not vulnerable as a result of including its own build of libxml. This update makes the security auditing green.

update nokogiri to address CVE-2017-9050

---

README.md

RK: noting obvious fix from [mortonfox](https://github.com/mortonfox)

update link to Mocha framework in docs

---

omnibus/Gemfile.lock

update embedded omnibus software to build against new libxml2 and libxslt
Addresses CVE-2017-0663, CVE-2017-7375, CVE-2017-7376, CVE-2017-9047,
CVE-2017-9048, CVE-2017-9049, CVE-2017-9050.
See https://github.com/chef/omnibus-software/pull/886

update embedded libxml2 and libxslt

---

src/supermarket/app/models/cookbook_version.rb
src/supermarket/app/views/cookbooks/_cookbook.html.erb
src/supermarket/app/views/cookbooks/_main.html.erb

CookbookVersion now knows how to compute a version's pass rate percentage for quality metrics.
Add that display with a gauge to search results and on the Quality tab of the cookbook version display page.

add QM pass rate percentage to search results, show page

---

src/supermarket/app/assets/stylesheets/listing.scss
src/supermarket/app/assets/stylesheets/tabs.scss
src/supermarket/app/models/cookbook_version.rb
src/supermarket/app/views/cookbooks/_cookbook.html.erb
src/supermarket/app/views/cookbooks/_main.html.erb
src/supermarket/config/locales/en.yml

Also show a "-" when there are no results with which to compute a pass rate.

add a tooltip to explain the metric pass rate display

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb

This is the start of removing interpolated values from the omnibus' cookbook attribute defaults. Interpolating the default chef_server_url into chef_identity_url in the defaults caused no end of trouble with onprem installations. The [application URL helpers](https://github.com/chef/supermarket/blob/c6970b5aeb95746c24386e7c8cb88000ea5c8790/src/supermarket/app/helpers/custom_url_helper.rb) already perform run-time interpolation with the chef_server_url when no env var is present. So we'll leave these attributes unset which will omit them from the list of things that get exported as env vars.
Administrators still have the option to set a value for these attributes which will set the associated env var and will override in the Rails app.

remove some interpolated default attributes for sensible ocid default

---

src/supermarket/app/lib/feature.rb

Be clear about:
1. Cannot instantiate a Feature object (module instead of class)
2. List of methods delegated to the "feature flag adapter" which happens to be Rollout in our implementation.
Thanks to @cupakromer and @keithrbennett for helpful suggestions.

use Forwardable for all the feature flag delegation

---

omnibus/Gemfile.lock
omnibus/config/projects/supermarket.rb

Going to let openssl use the default defined by the software definition because that's been the Chef default for a long time now.

set openssl to install the latest default in omnibus-software

---

.delivery/build_cookbook/metadata.rb
.delivery/build_cookbook/recipes/deploy.rb

See the following change for details: chef/cd-infrastructure#97

audit cookbook is now applied via an optional recipe

---

inspec/supermarket-smoke/controls/base.rb
inspec/supermarket-smoke/libraries/helper.rb

* Use SSL verifications by default now (our wildcard cert now covers
*.cd.chef.co)
* Extract the target host from the InSpec backend

InSpec smoke test improvements

---

src/supermarket/app/controllers/api/v1/cookbook_versions_controller.rb
src/supermarket/app/models/cookbook_version.rb
src/supermarket/spec/controllers/api/v1/cookbook_versions_controller_spec.rb
src/supermarket/spec/models/cookbook_version_spec.rb

I'm attempting to set up a private supermarket that is backed with S3 and uses presigned urls for access when downloading cookbooks.
While doing this I found that setting the `S3_URLS_EXPIRE` environment variable causes the cookbook download to fail with a 500 error. The error in the log states: `ArgumentError (comparison of String with 604800 failed)`. After some digging I found that the issue is caused by the `S3_URLS_EXPIRE` environment variable is always a string, and gets passed down to the aws-sdk via paperclip and hits a comparison that ensures the given expiry time is less than one week (604800 seconds).
This PR fixes this by always converting the string to a number when asking for the expiry_url.
I haven't been able to set up a proper dev environment for this, so I'm unsure if …

Convert S3_URLS_EXPIRE to a number on use

---

omnibus/config/projects/supermarket.rb

RubyGems 2.7.0-.3 seems to break the omnibus build with:
```
ERROR:  Error installing bundler:
"bundle" from bundler conflicts with /opt/supermarket/embedded/bin/bundle
```
Pinning to latest 2.6.x to fix the pipeline for release.
PEOPLE OF THE FUTURE, this pin should get revisited.

fix omnibus build, pin rubygems to 2.6.x

---

omnibus/config/projects/supermarket.rb

Addresses [CVE-2016-4450](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4450) (and possibly others to be determined)
Closes #1705

upgrade version of omnibus-embedded nginx

---

src/supermarket/Gemfile.lock

Only used to generate docs, but quiets vulnerability scanners because this upgrade addresses [CVE-2017-17042](https://nvd.nist.gov/vuln/detail/CVE-2017-17042)

upgrade yard

---

.delivery/build_cookbook/recipes/deploy.rb

Signed-off-by: Scott Hain <shain@chef.io>
@chef/jex-team @chef/ben-team

Converge runner with no fork

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/app/lib/active_model/validations/chef_version_validator.rb
src/supermarket/app/models/cookbook.rb
src/supermarket/app/models/cookbook_version.rb
src/supermarket/spec/models/cookbook_upload/parameters_spec.rb
src/supermarket/spec/models/cookbook_upload_spec.rb
src/supermarket/spec/models/cookbook_version_spec.rb
src/supermarket/spec/support/api_spec_helpers.rb

[A version for a cookbook must be either X.Y.Z or X.Y](https://docs.chef.io/cookbook_versions.html#constraints). Up until this change, the validation for a CookbookVersion's version was against SemVer rules. SemVer allows for release labels or build info to appear after the version number itself. Chef does not!
Here, we add a new ChefVersionValidator that reuses the existing version validation logic of the Chef gem in ::Chef::Version. Supermarket is already relying on the Chef gem to validate version constraints set for cookbook dependencies and supported platform.
Fixes #1714 to return an error to any client if a cookbook is uploaded with an invalid version.

Fix version validation against chef's required format

---

src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

Update Foodcritic to 12.3

---

omnibus/.kitchen.yml
omnibus/Gemfile.lock
omnibus/cookbooks/supermarket-builder/recipes/default.rb
src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

Upgraded the gem references for nokogiri and upgraded omnibus/-software for an updated libxml2 "system library." Addresses CVE-2017-15412
Also, remove `node.set` (deprecated) from dev build cookbook. `node.set` is deprecated. Use `node.default`/`node.override` ...  OR just set them in the kitchen config!

upgrade nokogiri & libxml2

---

src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

Addresses [CVE-2018-7212 reported in rack-protection](https://github.com/sinatra/sinatra/pull/1379). CVE does not affect Supermarket because the vulnerability is only on Windows platforms.

update rack-protection (addresses underlying CVE audit that does not apply to Supermarket installs)

---

src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

It's faster and has more rules

Update to Foodcritic 13.1.1

---

README.md

Gemnasium has been bought by GitLab and shuttered.

remove gemnasium badge from README

---

src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

Upgrade the Sprockets gem to patch for
[CVE-2018-3760](https://nvd.nist.gov/vuln/detail/CVE-2018-3760)
The actual sprockets CVE doesn't affect Supermarket because it does
not do asset compilation during the request/response cycle. However,
this will upgrade the gem to clear a bundle-audit failure.
Fixes #1742

Upgrade Sprockets [CVE-2018-3760]

---

src/fieri/Gemfile.lock
src/fieri/fieri.gemspec
src/supermarket/Gemfile.lock

Update Foodcritic to 14

---

.travis.yml
src/fieri/Gemfile.lock
src/supermarket/Gemfile.lock

The CVE alert bundle-audit produces does not really apply to Supermarket because the package built by omnibus uses libxml libraries directly, not the libxml2 libraries bundled with the nokogiri gem. But this change will quiet the gem audit.

update nokogiri to quiet gem audit finding

---

src/supermarket/app/helpers/markdown_helper.rb
src/supermarket/spec/helpers/markdown_helper_spec.rb

Fixes a bug in rendering links and images with unsafe protocols in the display of user-provided markdown.
[Redcarpet::Render::Safe](https://github.com/vmg/redcarpet/blob/v3.4.0/lib/redcarpet.rb#L25-L60) is the class provided by the library for rendering markdown provided by users (so not trustworthy). As of redcarpet v3.4.0, Safe's defaults are
* escape HTML characters
* skip rendering links and images with unsafe URLs
* not to include a code block's language in the tag
So we've switched to the Safe renderer and expanded the specs testing for preventing XSS injections into the rendered HTML.
Thanks to Sundarr Insa for reporting the behavior!

fix markdown rendering links and images with unsafe protocols

---

.expeditor/config.yml

This isn't doing anything at this point.

Remove deprecated maintainer_group config in expeditor

---

.travis.yml

The precise APT repo is no longer. Trusty is the release used by the workers at the moment, so let's use that.
Attempting to resolve:
```
Adding APT Sources (BETA)
Disallowing sources: chef-stable-precise
To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
```

use a supported Ubuntu release

---

.travis.yml
src/supermarket/lib/tasks/spec/all.rake

There is no fix released yet for the rubyzip vulnerability and it is only used by license_finder in the development environment.

ignore CVE-2018-1000544 (rubyzip)

---

.gitignore
habitat/README.md
habitat/default.toml
habitat/plan.sh

We've started work on packaging the Supermarket application with
Habitat. This is an initial skeleton via `hab plan init` so we can
point to a plan on Habitat Builder. This won't do anything yet, and
the package will be private for a time.

habitat skeleton to get started

---

omnibus/cookbooks/omnibus-supermarket/templates/default/rails.nginx.conf.erb
src/supermarket/app/views/cookbooks/_installs.html.erb
src/supermarket/app/views/cookbooks/directory.html.erb
src/supermarket/app/views/pages/dashboard.html.erb
src/supermarket/app/views/pages/welcome.html.erb

We're in the process of deprecating knife cookbook site in favor of knife supermarket which has been built into Chef for many years now.

change "knife cookbook site" references to "knife supermarket"

---

src/supermarket/Gemfile.lock

Appease CVE check that finds [CVE-2018-1000201](https://nvd.nist.gov/vuln/detail/CVE-2018-1000201):
> ruby-ffi version 1.9.23 and earlier has a DLL loading issue which can
> be hijacked on Windows OS
Supermarket does not run on Windows, so it is not affected by this CVE. This change is to help reduce the noise of CVE audits.

update ffi gem to reduce CVE audit noise

---

omnibus/cookbooks/omnibus-supermarket/templates/default/nginx.conf.erb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/inspec/controls/install-check.rb

Fixes MSYS-879
- By using 'server_tokens off' in the main nginx config file, version
number of the server can be omitted by default for any server entries
declared.
- Tests for version number omission were added to the internal cookbook
- [Similar changes were applied for chef-server](chef/chef-server#1514) by using
'more_clear_headers', but that would require 'Nginx-More' module,
hence we are using an nginx-only solution for the moment

omit web server version from response headers

---

.travis.yml
src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile.lock

Also, turn the check for CVE-2018-1000544 back on now that rubyzip had an update we updated to already.

update nokogiri to quiet CVE audit

---

omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/test.rb

`--format` was deprecated in 2.0 and removed in 3.0
Reorder the command built so that the switches come at the end. Use Inspec's reporter ability to write to an output file instead of doing the write ourselves in the ctl command.
```
vagrant@default-ubuntu-1604:~$ sudo supermarket-ctl test -J pedant.xml
vagrant@default-ubuntu-1604:~$ echo $?
0
vagrant@default-ubuntu-1604:~$ cat pedant.xml
<?xml version='1.0'?>
<testsuites>
<testsuite name='omnibus-supermarket-test' tests='27' failed='0' failures='0'>
<testcase name='Command: `supermarket-ctl console` stderr should match /supermarket-ctl console should be run as the supermarket OS user./' classname='omnibus-supermarket-test.supermarket-ctl-perms' target='local://' time='0.083338514'/>
<testcase name='Command: `supermarket-ctl make-admin` …
```

update omnibus ctl test command for Inspec 3.0

---

src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile.lock

loofah < 2.2.3 has a cross-site scriting vulnerability [reported](https://github.com/flavorjones/loofah/issues/154).
Supermarket is not vulnerable to this. The library is being updated out of an abundance of caution and to appease the vulnerability scanner.

upgrade loofah to 2.2.3

---

src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile.lock

Resolves bundle-audit finding for [CVE-2018-16471](https://groups.google.com/forum/#!topic/ruby-security-ann/NAalCee8n6o).

update rack for CVE-2018-16471

---

omnibus/cookbooks/supermarket-builder/metadata.rb
omnibus/cookbooks/supermarket-builder/recipes/default.rb

Modern Chef gives us apt_update out of the box. No need for the apt cookbook now.

Use the built-in apt resource in the omnibus build cookbook

---

omnibus/cookbooks/supermarket-builder/recipes/default.rb

This reverts commit c1a4ceed261dfe368fda441af5343b0c4d43baa9.
Turns out, the recursive directory permission applied by Chef's directory resource was insufficient to fix `.bundle/cache` being created and populated with stuff by root. So, let's go back to executing a chmod which worked a treat.

Revert "use Chef, not shell-out, to fix directory permissions"

---

omnibus/Gemfile.lock
omnibus/config/projects/supermarket.rb

In other projects we've seen up to a 30% reduction in the install size with this change.

remove unnecessary build cruft before packaging (reduces size ~12%)

---

omnibus/config/projects/supermarket.rb
omnibus/cookbooks/omnibus-supermarket/Berksfile
omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/test.rb
omnibus/cookbooks/omnibus-supermarket/libraries/config.rb
omnibus/cookbooks/omnibus-supermarket/recipes/config.rb
omnibus/cookbooks/omnibus-supermarket/recipes/rails.rb
omnibus/cookbooks/omnibus-supermarket/spec/libraries/config_spec.rb
omnibus/cookbooks/omnibus-supermarket/spec/recipes/config_spec.rb
omnibus/cookbooks/omnibus-supermarket/templates/rails.nginx.conf.erb
omnibus/cookbooks/omnibus-supermarket/templates/sv-nginx-run.erb
omnibus/cookbooks/omnibus-supermarket/templates/sv-rails-run.erb
omnibus/cookbooks/omnibus-supermarket/templates/sv-sidekiq-run.erb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/inspec/controls/install-check.rb
omnibus/omnibus.rb
src/supermarket/app/lib/supermarket/fips.rb
src/supermarket/config/initializers/fipsify.rb

Three of the five services that comprise Supermarket are identified as appropriate for enabling FIPS mode on:
* front-facing reverse web proxy (nginx): in single-server standalone environments nginx is responsible for SSL termination
* web application service (rails): some crypto is performed by the web service for user authentication via hashing secrets
* background jobs (sidekiq): no crypto for secrets is performed in background jobs as of this writing, but the jobs share a code base and runtime configuration with the web service, so enabling it is no more difficult
+ new `['supermarket']['fips_enabled']` item added to the omnibus install to explicitly enable or disable FIPS mode; the default is set to nil which the omnibus install will treat as "determine FIPS mode based on whether …

add FIPS 140-2 support

---

omnibus/config/projects/supermarket.rb

Removes the version pin for nginx in omnibus project. Updates omnibus-software to the latest which includes the latest nginx and an nginx software definition that sets the default version to the latest nginx. No longer need to keep changing the pinned version to get a newer release, just need to update omnibus-software.

upgrade omnibus-embedded nginx

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
omnibus/cookbooks/omnibus-supermarket/libraries/config.rb
omnibus/cookbooks/omnibus-supermarket/spec/libraries/config_spec.rb
src/supermarket/app/lib/supermarket/s3_config_audit.rb
src/supermarket/config/initializers/paperclip.rb
src/supermarket/spec/lib/supermarket/s3_config_audit_spec.rb

Signed-off-by: pavel-kazhavets <pavel.kozhevets@gmail.com>
Currently using supermarket with S3 cookbook storage requires having static IAM credentials in config file, which is not secure and requires manual key rotation.
Paperclip supports credentials from metadata endpoint (IAM instance profile), but supermarket won't start if `s3_access_key_id` and `s3_secret_access_key` are not present in the config.
This PR should fix https://github.com/chef/supermarket/issues/1724

add support for S3 storage using IAM roles (IAM user and a key no longer required)

---

omnibus/config/projects/supermarket.rb

Until Supermarket is ready for adding license acceptance, package it with a version of InSpec that does not require license acceptance.
-  ~I have updated the documentation accordingly.~
-  ~I have added tests to cover my changes.~

pin inspec to fix '-ctl test' requiring license acceptance

---

src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile.lock

Upgrade nokogiri required to quiet vulnerability scanners. Supermarket is packaged built against its own libxslt, not the one embedded in the nokogiri gem.

upgrade nokogiri (CVE-2019-11068)

---

.github/CODEOWNERS
README.md

In accordance with https://github.com/chef/chef-oss-practices/blob/master/repo-management/repo-states.md
* update README with project state and response times
* update CODEOWNERS to use the project Reviewers group

update repo to new Chef OSS practices

---

.expeditor/release.omnibus.yml
omnibus/.kitchen.yml
omnibus/README.md
omnibus/cookbooks/omnibus-supermarket/.kitchen.yml

Ubuntu 14 is EOL and has been removed from the build pipeline in favor of Ubuntu 16

No more Ubuntu 14 builds. Canonical ended support for trusty in April 2019.

---

omnibus/Gemfile
omnibus/Gemfile.lock

This change only affects CI. A new version of omnibus is required and the artifactory gem is required for the publish part of the build stage.
https://github.com/chef/omnibus-buildkite-plugin/issues/22

[ci] Add artifactory to omnibus/Gemfile

---

omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/version.rb

Matches [the version command in Chef Server](https://github.com/chef/chef-server/pull/1485)
Closes #1805 

add a version command to supermarket-ctl

---

src/supermarket/Gemfile.lock

This is an audit appeaser. Supermarket does not use rubyzip during operation. It comes in as a depencency of license_finder which is a dev/test time tool. This updates that gem, too.
Once merged, this should address the error seen in #1824.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

update rubyzip to address CVE-2019-16892

---

omnibus/cookbooks/omnibus-supermarket/libraries/config.rb

When the secrets.json already exists, the config items weren't getting added to the node. Let's fix that.

include secrets found in secrets.json in runtime omnibus config

---

CHANGELOG.md
omnibus/.kitchen.yml
omnibus/config/projects/supermarket.rb

RubyGems library embeds a version of bundler. To ensure we only have one version of bundler included in our package, rubygems and bundler must move together. This version of rubygems embeds bundler 1.17.3 which is the version of bundler the rest of Supermarket's components expects.

avoid Double Bundler by pinning rubygems version

---

omnibus/cookbooks/omnibus-supermarket/attributes/default.rb

As more people roll out restrictions on public ACLs for their S3 buckets to avoid being the next headline we're likely to see people running into problems with their internal supermarket.  The info they need is here in the repository but it's not easy to find. This change is to surface that in a place people can find directly from the cookbook README.
This is all commented out so we don't change the defaults, and I believe it falls under the obvious-fix guidelines.  I'm just surfacing work already done by another developer within the documentation.
N/A
- ~I have run the pre-merge tests …

Add s3_private_objects info to omnibus attributes

---

.travis.yml
omnibus/cookbooks/omnibus-supermarket/libraries/config.rb
omnibus/cookbooks/omnibus-supermarket/metadata.rb
omnibus/cookbooks/omnibus-supermarket/recipes/config.rb
omnibus/cookbooks/omnibus-supermarket/spec/libraries/config_spec.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/inspec/controls/install-check.rb

As described in #1839, secrets.json now wins for config values.
If a secret_key_base has been provided by an existing secrets.json file,
no problem so long as that file is the same across multiple web hosts.
If no secrets.json file is present and a secret_key_base value was
provided via supermarket.rb or supermarket.json, a warning is
presented that this value should really be in secrets.json and
the secrets.json file is generated with that value and used from there.
If no secrets.json file is present and no secret_key_base value was
provided, a warning is presented that a value is being generated. If
the installation has only one web host, the generated value is fine. If
the installation has 2 or more web hosts, the administrators are
required to ensure that the secrets.json file matches …

generate secrets.json with warning messages

---

.travis.yml
src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile
src/supermarket/engines/fieri/Gemfile.lock
src/supermarket/engines/fieri/lib/tasks/spec.rake
src/supermarket/lib/tasks/spec/all.rake

Given that we're auditing with GitHub and have Dependabot opening PRs to update dependencies, we need bundler-audit less than we need to work with Ruby 2.7+

Remove bundler-audit from tests; we're auditing with GitHub

---

src/supermarket/app/models/user.rb

> Lint/DeprecatedOpenSSLConstant:
>   Use `OpenSSL::Digest.hexdigest('MD5', key_in_der_format)` instead of
>   `OpenSSL::Digest::MD5.hexdigest(key_in_der_format)`.
[Rubocop has a new cop](https://github.com/rubocop-hq/rubocop/pull/7950) that detects an [upcoming deprecation to the OpenSSL gem](https://github.com/ruby/openssl/pull/366) that's built into Ruby.
The previous constant will cause failures in Ruby 3.
Closes #1859

Resolve upcoming OpenSSL Ruby library deprecation of algorithm constants

---

omnibus/cookbooks/supermarket-builder/recipes/default.rb

This tiny comment fix gets the cookstyle runs green against the omnibus
cookbooks

Minor comment fix to get full Cookstyle compliance in omnibus

---

.travis.yml
omnibus/config/projects/supermarket.rb

Updating to Ruby 2.6.6 resolves these 2 CVEs:
CVE-2020-10663: Unsafe Object Creation Vulnerability in JSON (Additional fix)
CVE-2020-10933: Heap exposure vulnerability in the socket library

Update Ruby to 2.6.6 to resolve 2 CVEs

---

.expeditor/release.omnibus.yml
omnibus/cookbooks/omnibus-supermarket/.kitchen.yml

Amazon Linux 2 is just RHEL 7 so anything supported on RHEL 7 is
supported there as well, but this way it shows up on the downloads page.

add packages for Amazon Linux 2 to the pipeline

---

docs/cookbookadoptiononsupermarket.md

As it stands now, there is no documented way for cookbook ownerships to be transferred on supermarket.chef.io. 
After much internal conversation, we've been able to document the steps we currently take when a question of cookbook ownership comes up, and expand those to include some very rare theoretical situations that might come up. Documenting it here allows us to consistently answer questions around this process, and provides us a way forward in uncharted situations. 
Signed-off-by: benny Vasquez <bvasquez@chef.io>

Documenting Cookbook transfer policy

---

omnibus/cookbooks/supermarket-builder/metadata.rb

I just bumped the omnibus cookbook to require 14 so we should require 14
here as well. It dropped 2 cookbook deps by removing build_essential

Require Chef 14+ in omnibus now

---

src/supermarket/app/models/cookbook.rb
src/supermarket/spec/api/cookbooks_root_spec.rb

Queries using the named ordering options and also joins with other tables were failing with:
ActionView::Template::Error: PG::AmbiguousColumn:
ERROR:  column reference "id" is ambiguous
LINE 1: SELECT DISTINCT cookbook_followers_count, id AS alias_0, "c…
Database query was traced to these ordering options in the Cookbook scopes.
Added tests for the API route and query parameters that triggered these errors. Added tablenames to the column references to pass the tests.
Fixes #1892

disambiguate columns used in query ordering

---

src/supermarket/app/controllers/exceptions_controller.rb

Rails 5.1 deprecated using `env` in controllers in favor of using `request.env`. This change switches to that and removes some methods that are not currently used anywhere.
The result of the `env` calls being in place is that the exception show page rendering would itself cause an exception. Thus, all errors become 500 errors which heightens the suspicion of upstream proxies and load balancers. The application logs also get filled with stacktraces for simple non-matched route errors which no body has time for.
Somewhat related to #1891 and its increased 500 errors. 

Fix exceptions thrown by displaying an error

---

omnibus/cookbooks/omnibus-supermarket/recipes/app.rb

The data for this file resource's content is really a simple Ruby Hash built up from node attributes, not a node object itself. Instead of relying on the .to_yaml behavior previously patched onto Hash, use plain old Ruby YAML.dump with the Hash instead.
Resolves new "NoMethodError: undefined method 'to_yaml' for Hash" error when chefspec'ing.

[omnibus] use YAML.dump to serialize simple hashes to disk

---

.expeditor/release.omnibus.yml
omnibus/.kitchen.yml
omnibus/cookbooks/omnibus-supermarket/.kitchen.yml

RHEL6 is coming up on end-of-life this month, November 2020. The RHEL6 builders for Supermarket packages are currently wedged and won't build. So, instead of investing a lot of labor in fixing them for an OS that is about to go out of support, let's stop building now.

drop support for RHEL6 builds

---

omnibus/cookbooks/omnibus-supermarket/recipes/app.rb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/inspec/controls/install-check.rb
src/supermarket/config/environments/production.rb

Work in progress.
Fixes #1853 

add HTTP strict transport security header when force SSL is enabled

---

omnibus/omnibus-test.sh

This logic has been moved into the Omnibus Buildkite Plugin.
These scripts can now be used outside of the Buildkite pipelines.
Signed-off-by: Tom Duffield <github@tomduffield.com>

Remove pipeline-specific logic from test scripts

---

omnibus/config/projects/supermarket.rb

This includes multiple CVE fixes

Update PostgreSQL to 9.3.25

---

omnibus/config/software/supermarket.rb
src/supermarket/Gemfile

Exclude doc from the bundle install and move chefstyle back to
development.

Make sure chefstyle and yard aren't in the package

---

src/supermarket/app/views/cookbooks/directory.html.erb
src/supermarket/spec/views/cookbooks/directory.html.erb_spec.rb

Text change - `test-kitchen` should be changed to `Test Kitchen` in page cookbooks-directory.
Change of text to `Test Kitchen` in page directory.html.erb to match the requirements
https://github.com/chef/supermarket/issues/1974

Changed text test-kitchen to Test Kitchen

---

src/supermarket/app/views/pages/welcome.html.erb
src/supermarket/spec/views/pages/welcome.html.erb_spec.rb

Text changes on welcom.html.erb 
Changed text `Chef cookbooks` to `Chef Infra Cookbooks`
https://github.com/chef/supermarket/issues/1972

Changes Chef cookbooks text to Chef Infra Cookbooks as per issue

---

src/supermarket/app/views/cookbooks/directory.html.erb
src/supermarket/spec/views/cookbooks/directory.html.erb_spec.rb

Chef Development Kit(Chef-DK) on cookbooks-directory page was pointing to wrong link. Corrected the same
Chef DK link now points to https://downloads.chef.io/tools/workstation as was mentioned in the issue
https://github.com/chef/supermarket/issues/1975

Changed link for chef dk in directory file

---

src/supermarket/app/views/layouts/application.html.erb

Botbot irc logs link has to be removed from side panel
Removed the link from view `Botbot IRC Logs`
https://github.com/chef/supermarket/issues/1971
- [] I have added tests to cover my changes.

Removed link botbotirc from application.html file

---

src/supermarket/app/helpers/custom_url_helper.rb
src/supermarket/app/views/layouts/application.html.erb
src/supermarket/spec/helpers/custom_url_helper_spec.rb

Updated the links in footer which were redirects to progress.com earlier
Footer links are currently pointing to chef.io which are re-directed to progress.com later. I updated the link address to point to progress ip only
https://github.com/chef/supermarket/issues/1967

Added new url helper for progress.com and updated footer links

---

src/supermarket/app/models/tool.rb

- This change removes "Provisioning Driver" from tools directory from https://supermarket.chef.io/tools-directory
- Tested the change in my local dev setup
Fixes https://github.com/chef/supermarket/issues/1968

Remove provisioning driver from tools directory

---

README.md

Updated readme
Added missing steps and how to fix guidelines

Updated readme; Added missing steps and how to fix guidelines;

---

src/supermarket/app/views/cookbooks/directory.html.erb
src/supermarket/app/views/pages/dashboard.html.erb
src/supermarket/app/views/pages/documentation.html.erb
src/supermarket/app/views/pages/welcome.html.erb

Removed the .html from the docs links all over the app. 
Updated redirects such as /knife -> /workstation/knife as well.
https://github.com/chef/supermarket/issues/1965

Changes for removing .html from docs links

---

omnibus/config/software/supermarket.rb
src/supermarket/app/lib/supermarket/s3_config.rb

Our buildkite pipeline sets this now for the s3 caching of artifacts.
This is new and is causing the logic that makes sure that we have all
the necessary S3 env vars set to fail. Nuke that env var during the
build so the logic doesn't fire.

Fix S3_BUCKET validation failures in buildkite + improve error messages

---

omnibus/config/software/supermarket-cookbooks.rb

The berks install is causing failures since it deps on chef/chef and
pulls in the latest which only works on Ruby 2.7+

Don't install berks now that it's in omnibus-toolchain

---

src/supermarket/app/controllers/cookbooks_controller.rb
src/supermarket/app/models/cookbook.rb
src/supermarket/spec/controllers/cookbooks_controller_spec.rb
src/supermarket/spec/models/cookbook_spec.rb

We are sorting cookbooks with deprecated boolean field. Which will make sure, cookbooks which are deprecated are always shown at the end of the list on view
https://github.com/chef/supermarket/issues/1838

Changes for sorting cookbooks with deprecated flag

---

omnibus/config/software/supermarket.rb

This was fixed in our buildkite plugin

Back out the s3_region env var workaround

---

omnibus/config/software/supermarket.rb
omnibus/cookbooks/omnibus-supermarket/Gemfile
src/supermarket/Gemfile
src/supermarket/Gemfile.lock

- nodejs-binary is newer, faster to install, and easier to remove
- install yarn to prevent the rake job from failing
- remove sprockets which is what this was all for since it's built into rails now and we don't need double dep declarations
- further fix the cookbook gemfile so the ctl command can install

Switch to the binary install of nodejs and install yarn

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/app/controllers/api/v1/cookbook_versions_controller.rb
src/supermarket/app/controllers/cookbook_versions_controller.rb
src/supermarket/app/controllers/cookbooks_controller.rb
src/supermarket/app/controllers/transfer_ownership_controller.rb
src/supermarket/config/brakeman.ignore

Fixed vulnerable redirection errors by Brakeman. Added non vulnerabilities in brakeman ignore list.
Have fixed the real vulnerabilities of redirection by adding only path instead of complete URL with host. Also identified the non vulnerabilities and added them to the Brakeman ignore list.
[https://github.com/chef/supermarket/issues/2016](https://github.com/chef/supermarket/issues/2016)

Fixed redirection errors identified by Brakeman

---

omnibus/Gemfile.lock

The new omnibus-software definition brings in nginx 1.20.1
Fixes https://github.com/chef/supermarket/issues/1953

update deps: includes nginx 1.20.1

---

.expeditor/release.omnibus.yml

This change enables FIPS onto Ubuntu builds
Fixes https://github.com/chef/supermarket/issues/1956

Enable FIPS for the Ubuntu builds

---

omnibus/config/software/supermarket.rb

This is part of Ruby 2.7 so there's no need to isntall bundler again

Remove bundler install in omnibus

---

omnibus/config/software/supermarket.rb

Remove the binary nodejs

---

omnibus/cookbooks/omnibus-supermarket/Gemfile

This reduces our install size by over 100 megs by removing
azure/google/aws sdks that we're not actually using

Switch from inspec to inspec-core

---

omnibus/config/software/supermarket-ctl.rb

This avoids bringing in a big pile of extra stuff

Skip the test group when installing the ctl cookbook

---

omnibus/config/software/supermarket.rb

See if this fixes the build
https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/146#3c1ba9e2-d573-4ff7-8802-6b5666c528e7

Add .bundle back to the supermarket install as possible

---

omnibus/config/projects/supermarket.rb
omnibus/config/software/supermarket-ctl.rb
omnibus/cookbooks/omnibus-supermarket/Gemfile

This avoids EOL warnings in the ctl commands.

Use Chef Infra Client 16.14 in supermarket-ctl

---

omnibus/config/projects/supermarket.rb
omnibus/config/software/more-ruby-cleanup-supermarket.rb

This should drop the install size by 70 megs

Add a cleanup definition for all the gem cache junk

---

omnibus/cookbooks/omnibus-supermarket/Gemfile

This avoids a huge pile of deps that come with inspec

Switch from inspec-bin to inspec-core-bin

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/app/helpers/markdown_helper.rb
src/supermarket/spec/helpers/markdown_helper_spec.rb

substituting html comments with blank string in changelog text for a cookbook. 
Updated RedCarpet implementation to match the github markdown rendering standards. Mainly focussed on below two points : - 
1. Syntax highlighting ( used Code-ray for same ) 
2. Delete html comments  from the markdown content 
The above two points are also highlighted by @robbkidd  here -> https://github.com/chef/supermarket/issues/1321 
HTMLpipeline implementation could never be successfull. As its requiring a lot many behavioural changes as application is behaving as of now .. with some serious XSS attacks getting open like injection of javascript via href tag
https://github.com/chef/supermarket/issues/1831

Improve markdown rendering is changelogs / readmes

---

src/supermarket/Gemfile
src/supermarket/app/helpers/markdown_helper.rb

Previous PR had lint issues and got merged .. hence raising one more with fixes
Resolved lint issues 
Chefstyle -a changes committed during this PR 
https://github.com/chef/supermarket/issues/1831

chefstyle changes

---

src/supermarket/app/views/cookbooks/directory.html.erb

Swap Foodcritic for Cookstyle
Remove Berkshelf
Add Sous Chefs
Remove the whole section about cookbooks chef maintains since we're
moving away from that.

Better describe cookbooks and update links

---

src/supermarket/.rubocop.yml
src/supermarket/engines/fieri/.rubocop.yml

We're on Ruby 2.7 now so we should target Ruby 2.7

Update the ruby release in the rubocop configs to 2.7

---

src/supermarket/app/views/profile/edit.html.erb

There was a need to show a prompt to user for confirmation before he goes ahead and delete himself as collaborator from Edit profile page
https://github.com/chef/supermarket/issues/2140

Added prompt before delete action for collaborator

---

omnibus/config/software/supermarket.rb
omnibus/cookbooks/omnibus-supermarket/templates/nginx.conf.erb
omnibus/cookbooks/omnibus-supermarket/test/integration/default/inspec/controls/install-check.rb

- Removed nginx and added openresty
- Hide server header from API response
- Removed nginx header from API response([#1978](https://app.zenhub.com/workspaces/sustaining-engineering-progress-60c9e8f0307f65000e50585a/issues/chef/supermarket/1978))

Hide nginx server header from response

---

src/supermarket/app/helpers/custom_url_helper.rb
src/supermarket/spec/helpers/custom_url_helper_spec.rb

Supermarket production env is setting value for this env variable ENV[CHEF_WWW_URL] to `chef.io`. Since this env variable is getting used at some other place in application too, I am introducing a new env variable - ENV[PROGRESS_WWW_URL] which will have a value as `www.progress.com`  and will resolve error we are getting in footer url
https://github.com/chef/supermarket/issues/2155

Changes for progress url being picked from wrong ENV variable

---

.github/workflows/unit.yml
src/supermarket/app/controllers/profile_controller.rb
src/supermarket/app/views/api/v1/users/show.json.jbuilder
src/supermarket/app/views/profile/edit.html.erb
src/supermarket/app/views/users/_sidebar.html.erb
src/supermarket/db/migrate/20210823093118_add_slack_columns_to_users.rb
src/supermarket/db/migrate/20210823102104_remove_irc_columns_from_users.rb
src/supermarket/spec/api/user_show_spec.rb
src/supermarket/spec/controllers/profile_controller_spec.rb
src/supermarket/spec/features/edit_profile_spec.rb
src/supermarket/spec/views/api/v1/users/show.json.jbuilder_spec.rb

- Removed irc_nickname from users table, user edit profile and view profile
- Added slack_username in users table, user edit profile and view profile
- Added db migrate step before running unit tests (spec)
#2150  #2173

Added slack username and removed irc nickname from user profile

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/config/initializers/session_store.rb

Upgraded Omniauth gem to 2.0.0 and related gem upgrade - omniauth-github and omniauth-oauth2
Changed the config file to allow session creation in dev mode as well. When the session is not created in dev mode, it's impossible to get through omniauth token verification
https://github.com/chef/supermarket/issues/1903
https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/188

Omniauth gem upgrade to 2.0

---

.gitignore
src/supermarket/app/assets/stylesheets/application.css.scss
src/supermarket/app/assets/stylesheets/mobile_search.scss

Signed-off-by: saghoshprogress <saghosh@progress.com>
Updated the CSS for mobile search
[ISSUES](https://app.zenhub.com/workspaces/sustaining-engineering-progress-60c9e8f0307f65000e50585a/issues/chef/supermarket/1226)

Updated the CSS for mobile search

---

omnibus/config/software/more-ruby-cleanup-supermarket.rb

- Fixed the way cache directory can be deleted under ruby version directory in omnibus artifact.
Wildcard(*) doesn't work with `remove_directory`. Hence iterating over the directory to identify individual ruby version directory to delete specific folders under each ruby version.
#1951

Rajeshpaul38/remove omnibus artifact vendor cache dir/1951

---

src/supermarket/config/initializers/content_security_policy.rb

Constent security policy is stopping inline css to function. We need to allow usage of inline css for the app UI to work , dropdowns were not rendering due to the same error 
https://github.com/chef/supermarket/issues/2254

Changes for Content security policy to allow inline css

---

src/supermarket/app/models/tool.rb

Renamed "handler" type to "Chef Infra Handler" 
This change will make sure user selects `Chef Infra Handler` while creating a tool
https://github.com/chef/supermarket/issues/1970

Changed name of allowed types to Chef Infra Handler

---

src/supermarket/app/controllers/api/v1/cookbooks_controller.rb
src/supermarket/spec/api/cookbook_search_spec.rb
src/supermarket/spec/controllers/api/v1/cookbooks_controller_spec.rb
src/supermarket/spec/controllers/api/v1/tools_controller_spec.rb

…uery
Currently total that is included as part of the search api call is the total number of records retrieved as part of search. I have changed it to return total number of cookbooks in the system. 
https://github.com/chef/supermarket/issues/1827

Changes for Cookbook count to be included in total items search api

---

omnibus/cookbooks/omnibus-supermarket/recipes/config.rb
omnibus/cookbooks/omnibus-supermarket/spec/recipes/config_spec.rb

Supermarket user created as part of build installation has to be a system user. Changed the recipe in omnibus-supermarket cookbook to create user as system-user
[
](url)
Recipe already throws error in case group `supermarket` exists on the system already. As per the issue that was also the concern
https://github.com/chef/supermarket/issues/1179

Recipe change to create supermarket as system user

---

src/supermarket/config/application.rb

Changed  rails autoloader version from 5.1 to 6.0
With the older version it was failing to autoload namesapced classes under app/model. Hence running **reload!** in rails console doesn't reload such classes. With this change the auto-reloading works perfectly. This doesn't add any feature but will help developers test their changes seamlessly without being needed to restart rails console every time for testing  any changes.
#2378

Changed rails autoloader version from 5.1 to 6.0

---

src/supermarket/app/controllers/cookbooks_controller.rb
src/supermarket/app/models/cookbook.rb
src/supermarket/app/views/cookbook_mailer/cookbook_deprecated_email.html.erb
src/supermarket/app/views/cookbook_mailer/cookbook_deprecated_email.text.erb
src/supermarket/app/views/cookbooks/_main.html.erb
src/supermarket/app/views/cookbooks/_manage_cookbook.html.erb
src/supermarket/app/views/cookbooks/_sidebar.html.erb
src/supermarket/config/locales/en.yml
src/supermarket/db/migrate/20211021105430_add_deprecation_reason_to_cookbooks.rb
src/supermarket/db/schema.rb
src/supermarket/spec/controllers/cookbooks_controller_spec.rb
src/supermarket/spec/features/cookbook_undeprecation_spec.rb
src/supermarket/spec/models/cookbook_spec.rb
src/supermarket/spec/views/cookbook_mailer/cookbook_deprecated_email.html.erb_spec.rb
src/supermarket/spec/views/cookbooks/show.html.erb_spec.rb

Added new field to add custom reason while deprecating the cookbook and also replaced icon with text if there is not supported platforms given for cookbook.
Fixed: 1) https://github.com/chef/supermarket/issues/2193
2) https://github.com/chef/supermarket/issues/2250

Allow adding reason to cookbooks when deprecated

---

docs-chef-io/content/supermarket/install_supermarket.md

Signed-off-by: kagarmoe <kgarmoe@chef.io>

Increase memory requirement

---

src/supermarket/app/models/tool.rb

On the UI tool type has to appear as Chef Infra Tool instead of Chef tool
In model class, in allowed types array for tool changed chef_tool to chef_infra_tool
https://github.com/chef/supermarket/issues/1969

Rename chef_tool to chef_infra_tool

---

src/supermarket/app/views/cookbooks/_installs.html.erb
src/supermarket/spec/views/cookbooks/show.html.erb_spec.rb

Signed-off-by: Manick Vel <mkumaravel@msystechnologies.com>
This issue requires Policyfile tab to be placed at first and by default ahead of Berkshelf in the cookbooks directory - cookbook page. Before this change, Bershelf was meant to be the default and first tab. 
https://github.com/chef/supermarket/issues/2252
- [] PR title is a worthy inclusion in the CHANGELOG

Policyfile change to default and first tab in cookbook page

---

omnibus/Gemfile.lock
src/supermarket/Gemfile
src/supermarket/Gemfile.lock

Merge these PRs:
Bump spring from 3.1.1 to 4.0.0 in /src/supermarket -> https://github.com/chef/supermarket/pull/2435
Bump omnibus from 2c309fa to 2bf77bb in /omnibus -> https://github.com/chef/supermarket/pull/2434
Bump chef from 17.7.29 to 17.8.25 in /src/supermarket -> https://github.com/chef/supermarket/pull/2421

Rajeshpaul38/dependabot pr merge/2436

---

.github/CODEOWNERS
.github/labeler.yml
.github/workflows/labeler.yml

Make sure the docs team always knows when a docs thing changes

Configure labeller to auto asign docs PRs

---

src/supermarket/.rubocop.yml

Signed-off-by: Siraj Rauff <sirajrauff@gmail.com>

Adding Habitat Configuration files to Rubocop exclude

---

docs-chef-io/content/supermarket/config_rb_supermarket.md
omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
src/supermarket/config/environments/production.rb
src/supermarket/engines/fieri/app/controllers/fieri/jobs_controller.rb

In current setup quality metrics job is not running, A CSRF authentication token error is throws in from the controller when worker tries to make an http request there. 
Also rails default configuration in `production.rb` is redirecting `http://localhost` to`https://localhost` and hence its not served by the application either
https://github.com/chef/supermarket/issues/2400

Changes for jobs controller to not to throw CSRF token authentication error

---

.github/workflows/unit.yml

Don't run unit tests on documentation

Exclude docs from unit tests

---

docs-chef-io/content/supermarket/_index.md
docs-chef-io/content/supermarket/config_rb_supermarket.md
docs-chef-io/content/supermarket/ctl_supermarket.md
docs-chef-io/content/supermarket/install_supermarket.md
docs-chef-io/content/supermarket/supermarket_api.md
docs-chef-io/content/supermarket/supermarket_backup_restore.md
docs-chef-io/content/supermarket/supermarket_logs.md
docs-chef-io/content/supermarket/supermarket_monitor.md
docs-chef-io/content/supermarket/supermarket_private.md
docs-chef-io/content/supermarket/supermarket_share_cookbook.md

Set product to "supermarket" so we can filter pages in Swiftype search results by Supermarket.
See  chef/chef-web-docs#3625

Set product in search to supermarket

---

docs-chef-io/content/supermarket/ctl_supermarket.md
src/supermarket/app/controllers/api/v1/cookbook_uploads_controller.rb

SPDX license linking ctl commands need to have related documentation as well. 
https://github.com/chef/supermarket/issues/2188

SPDX-CTL command documentation and cookbook_upload change

---

src/supermarket/app/helpers/custom_url_helper.rb
src/supermarket/spec/helpers/custom_url_helper_spec.rb

Signed-off-by: Manick Vel <mkumaravel@msystechnologies.com>
Change chef downloads url from downloads.chef.io to https://www.chef.io/downloads
https://github.com/chef/supermarket/issues/2350

Change chef downloads url

---

docs-chef-io/content/supermarket/_index.md
docs-chef-io/content/supermarket/config_rb_supermarket.md
docs-chef-io/content/supermarket/ctl_supermarket.md
docs-chef-io/content/supermarket/install_supermarket.md
docs-chef-io/content/supermarket/supermarket_api.md
docs-chef-io/content/supermarket/supermarket_backup_restore.md
docs-chef-io/content/supermarket/supermarket_logs.md
docs-chef-io/content/supermarket/supermarket_monitor.md
docs-chef-io/content/supermarket/supermarket_share_cookbook.md

Signed-off-by: kagarmoe <kgarmoe@chef.io>
Update markdown formatting. Many of the documentation lints rely on well-formatted markdown.

Markdown formatting.

---

docs-chef-io/content/supermarket/ctl_supermarket.md

Typo in spdx ctl command documentation fixed
Issue was reported on slack - https://chefio.slack.com/archives/C0272A81LA1/p1640903043088700

Corrected typo in spdx documentation

---

docs-chef-io/content/supermarket/_index.md

This makes no sense. We should be linking to the package download instead.

Remove the private supermarket source link

---

docs-chef-io/content/supermarket/config_rb_supermarket.md
omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
omnibus/cookbooks/omnibus-supermarket/recipes/config.rb
omnibus/cookbooks/omnibus-supermarket/recipes/sidekiq.rb

Signed-off-by: saghoshprogress <saghosh@progress.com>
Added option to modify the log directory permission, default will remain the same.
[Issues](https://app.zenhub.com/workspaces/sustaining-engineering-progress-60c9e8f0307f65000e50585a/issues/chef/supermarket/1856)
https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/264#1c7d3371-3a9e-4019-a442-831b6b23c7a2

Updated the log directory permission

---

.github/workflows/lint.yml
src/supermarket/engines/fieri/Gemfile
src/supermarket/engines/fieri/app/controllers/fieri/jobs_controller.rb
src/supermarket/engines/fieri/app/models/cookbook_artifact.rb
src/supermarket/engines/fieri/app/models/cookstyle_worker.rb
src/supermarket/engines/fieri/lib/quality_metric/cookstyle_helpers.rb
src/supermarket/engines/fieri/spec/models/cookbook_artifact_spec.rb
src/supermarket/engines/fieri/spec/models/cookstyle_worker_spec.rb
src/supermarket/engines/fieri/spec/rails_helper.rb

Fieri chefstyle was not getting executed due to /engines folder being excluded in rubocop.yml  for main src directory.
Ran chefstyle using 
`bundle exec chefstyle --ignore-parent-exclusion` 
and also updated chefstyle command in workflow configuration

Chefstyle failures corrected for fieri engine

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile.lock
src/supermarket/engines/fieri/fieri.gemspec

Signed-off-by: saghoshprogress <saghosh@progress.com>
Updated the sidekiq gem for FIX [CVE](https://github.com/TUTUMSPACE/exploits/blob/main/sidekiq.md) 
Build
https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/330

Updated sidekiq gem

---

src/supermarket/app/helpers/application_helper.rb
src/supermarket/config/initializers/omniauth.rb
src/supermarket/spec/helpers/application_helper_spec.rb
src/supermarket/spec/views/profile/edit.html.erb_spec.rb

- Fixed GITHUB Enterprise conditions to display GITHUB account as default.

Fixed github enterprise condition check.

---

omnibus/cookbooks/omnibus-supermarket/templates/nginx.conf.erb

- Fixed Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.

Fixed Error with Permissions-Policy header: Parse of permissions policy

---

src/supermarket/engines/fieri/.rubocop.yml
src/supermarket/engines/fieri/lib/quality_metric/cookstyle_helpers.rb

Rubocop cop - `Chef/Ruby/UnlessDefinedRequire` , stops the file from loading a module in case its already loaded. 
This is causing issues since rails zeitwerk tries to autoload all the dependencies beforehand but in few cases the dependencies are not loaded properly and hence need to be re-loaded on the run time. This was breaking the execution of cookstyle and hence the cop is disabled.
chefstyle autocorrection in engines directory broke the running cookstyle metric feature.

Added clause to ignore cop UnlessDefinedRequire in rubocop.yml

---

omnibus/config/projects/supermarket.rb

Latest version of logrotate from omnibus-software causes build to fail.

Pin logrotate dependency

---

omnibus/README.md

Removed the '$' character so that we can copy just the command by clicking copy button.
Need to remove the `$` promt. If this stays as part of the command then when user copies the command using the copy button it also copies the `$` character which when executed from the terminal throws error saying `unknown command $`
INFSUS-55

Removed unnecessary prompt '$'

---

README.md

It doesn't make much sense to call these out as requirements since this is all packages. If we want to call out the currently packaged tools and what you would need for development that should live elsewhere.

Remove requirements since these are bundled

---

.bldr.toml
.expeditor/build.habitat.yml
.expeditor/config.yml
.expeditor/verify.habitat-packages.yml

Added expeditor configs to check the habitat build.
We need to test the build for habitat for this build https://github.com/chef/supermarket/pull/2453

Added Expeditor configs to check habitat build

---

README.md

added steps to fix gem installation issue for therubyracer and libv8
INFSUS-61

added steps to fix gem installation issue for therubyracer and libv8

---

omnibus/config/software/supermarket.rb

Signed-off-by: Dheeraj Singh Dubey <dhsingh@progress.com>
-- Remove git dependency
Fixes : #1959

Remove git dependency

---

src/supermarket/app/views/application/_analytics.html.erb
src/supermarket/config/initializers/content_security_policy.rb

Updated content security policy to allow script and style from google analytics

---

docs-chef-io/content/supermarket/config_rb_supermarket.md
omnibus/cookbooks/omnibus-supermarket/attributes/default.rb
src/supermarket/.env
src/supermarket/config/environments/production.rb

This PR is to create a provision for the customers of supermarket to either allow/disallow the protection against host header injection attack. This is to resolve the issue where supermarket runs behind an AWS ELB and when the ELB performs the healthcheck against the target instance the healthcheck API responds with status code 403 (forbidden). Now this flag will allow the customers to disable the protection and allow arbitrary host headers in the API calls thus allowing the ELB healthcheck operation.
https://github.com/chef/supermarket/issues/2628

Created provision to enable or disable protection from host header attacks

---

docs-chef-io/netlify.toml

Remove Hugo version and go version from netlify config. The current specified Hugo version has a bug that's making build failures in PR previews, and it's easier to update and specify these in the Netlify Web UI.

Remove hugo and go version from Netlify config

---

src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile
src/supermarket/engines/fieri/Gemfile.lock
src/supermarket/engines/fieri/fieri.gemspec
src/supermarket/engines/fieri/spec/models/cookstyle_worker_spec.rb

This is required for the cookbook quality metrics. Also unppin chefstyle and remove rubocop. Let the gemfile.lock do what it does best here.

Make cookstyle a runtime dep for Fieri

---

omnibus/Gemfile.lock
src/supermarket/Gemfile
src/supermarket/Gemfile.lock
src/supermarket/engines/fieri/Gemfile.lock

This PR is a bundle of the below PRs:
https://github.com/chef/supermarket/pull/2781
https://github.com/chef/supermarket/pull/2780
https://github.com/chef/supermarket/pull/2777
https://github.com/chef/supermarket/pull/2775
https://github.com/chef/supermarket/pull/2774
https://github.com/chef/supermarket/pull/2754

Upgrade dependencies: omnibus-software, sidekiq-cron, sidekiq, octokit, ddtrace

---

docs-chef-io/Makefile
docs-chef-io/content/supermarket/_index.md
docs-chef-io/content/supermarket/config_rb_supermarket.md
docs-chef-io/content/supermarket/ctl_supermarket.md
docs-chef-io/content/supermarket/install_supermarket.md
docs-chef-io/content/supermarket/supermarket_api.md
docs-chef-io/content/supermarket/supermarket_private.md
docs-chef-io/layouts/shortcodes/supermarket/supermarket_api_summary.md
docs-chef-io/layouts/shortcodes/supermarket/supermarket_private.md
docs-chef-io/layouts/shortcodes/supermarket/supermarket_summary.md

- Move shortcodes that belong in supermarket from `chef-web-docs` to `supermarket`.
- Delete shortcodes used only once and place text in page.
- Replace any use of `readFile_shortcode` shortcode with `readfile` shortcode.
- Update any shortcodes moved from `chef-web-docs` to other repositories.
- Update/improve docs makefile used by Netlify.
https://chefio.atlassian.net/browse/CHEFDOCS-199

Move shortcodes used in supermarket docs to supermarket repo.

---

src/supermarket/Gemfile
src/supermarket/Gemfile.lock

This reverts commit 3aeb3a2341a304f8a7cb17e1f0a1d2e57a2d5e71.

Revert "Bump ddtrace from 1.0.0 to 1.1.0 in /src/supermarket"

---

docs-chef-io/content/supermarket/install_supermarket.md
docs-chef-io/content/supermarket/supermarket_upgrade.md

As part of the oc-id upgrade, it was  found that one of the main gem Doorkeeper has two  security vulnerability issues:
- [CVE-2018-1000211](https://nvd.nist.gov/vuln/detail/CVE-2018-1000211)
- [CVE-2020-10187](https://nvd.nist.gov/vuln/detail/CVE-2020-10187)
Consequentially,  doorkeeper gem has been upgraded from version 4.3 to use 5+. As a part of the doorkeeper upgrade, there has been few updates  in the authorization of applications such as Supermarket with `oc-id` or Chef-Identity. 
The same change that would entail this upgrade has been outlined here: [Supermarket authorization with Chef Identity](https://chefio.atlassian.net/wiki/spaces/TP/blog/2023/09/18/2816737399/Supermarket+authorization+with+Chef+Identity)
This PR aims to update `install_supermarket.md` file to reflect the …

Update doc for supermarket configuration with Chef Identity

---

docs-chef-io/content/supermarket/config_rb_supermarket.md

Add documentation changes for following feature flags
- gtm_id
- enable_onetrust
- enable_gtm
- enable_gtag

add doc changes for feature flag and gtm_id

---

src/supermarket/config/initializers/content_security_policy.rb

Whitelisting urls to resolve errors related to GTM in supermarket 
Demo: [Whitelist_url_supermarket_gtm_demo.mov](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/ERnfqMxfTLBMsLCzN6sNCVUBR6XjMXIiuJpoD7HgeB09_A?e=CHxFOa)
- x ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>

CHEF-6076:Whitelisting urls for GTM

---

.github/workflows/docs-lint.yml
.github/workflows/labeler.yml

Fix the GitHub actions
- the labeler action runs from the main branch, but was updated with breaking changes so now it blows up on every PR. This pins it to V4 of the labeler.
- I replaced the cspell.json with a YAML file so it's easier to read. This update should pull the correct file now.
- update other action deps

Fix issues with github actions

---

docs-chef-io/content/supermarket/supermarket_upgrade.md

Currently the instructions to upgrade supermarket misses one step for which the reconfigure operation fails. This PR is to add the missing step in the public docs of supermarket which will fix this issue faced by customers.
[CHEF-16756](https://progresssoftware.atlassian.net/browse/CHEF-16756)
[CHEF-16756]: https://progresssoftware.atlassian.net/browse/CHEF-16756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

supermarket upgrade instruction fix
